### ISSUE TITLE
Org-Agenda Issue

### ISSUE THREAD

**Issue by Bee-Mar** [emacs-dashboard/emacs-dashboard#100]
Sorry to open another issue on the same day, but with the latest update to `emacs-dashboard`, when I attempt to open an org-agenda item, I receive an error message. I attempted to do a clean re-install of emacs with my configuration, but recieved the same error. I also attempted a clean reinstall and used a test directory with a single org file that contained a single `TODO` set as my only org-agenda file. Opening org-agenda in the old-fashioned way works normally, and there is no error produced in that manner.

This is the format of the error message output whenever I attempt to open an item.

`
nth: Invalid function: #(" 2019-03-02 Discuss application overview (tentative schedule) ::" 0 13 (org-category "test" tags ("") org-highest-priority 65 org-lowest-priority 67 time-of-day nil ...) 13 62 (org-heading t org-category "test" fontified nil tags ("") org-highest-priority 65 ...) 62 65 (org-heading t org-category "test" tags ("") org-highest-priority 65 org-lowest-priority 67 ...))
`

**Comment by jkdufair** [comment]
I'm able to replicate this. I'll get a PR in shortly.
