### ISSUE TITLE
Show empty sections?

### ISSUE THREAD

**Issue by jkdufair** [emacs-dashboard/emacs-dashboard#105]
If someone has, i.e. registers specified in their `.emacs` and they don't have any registers defined, what should the behavior be?

1. Don't show the section at all?
1. Show something like "--- none ---" as the section text?
1. Show only the header?

I know agenda handles this specifically. For others, I believe my preference would be the first.

**Comment by JesusMtnez** [comment]
In my opinion, I think the preferred option is number 2. Not showing the section could lead to confusion, it would seem that the section is not being loaded. I think handling no elements as in the agenda widget would be the most reasonable way. 

I think the best way to handle that is to provide a way of handling no items in a widget in a general way if possible.

What do you think @rakanalh ?

**Comment by rakanalh** [comment]
I think previously (1) was implemented. But now i would prefer (2) as i agree (1) would lead to confusion.
