### ISSUE TITLE
Request: bullets and icons

### ISSUE THREAD

**Issue by ema2159** [emacs-dashboard/emacs-dashboard#116]
Could you add icons to the sections and bullets to the section items? I think it could improve a lot the way dashboard looks

**Comment by ema2159** [comment]
I did it myself with a couple of extra features. I'll create the pull request

**Comment by JesusMtnez** [comment]
Thank you @ema2159 . I was thinking of working on something similar using some work emacs centaur did it integrating `all-the-icons`.
