### ISSUE TITLE
Can not select item when using icons

### ISSUE THREAD

**Issue by JesusMtnez** [emacs-dashboard/emacs-dashboard#128]
Using `RET` to select an item from Emacs dashboard when the cursor is at the beginning of the line, just before the icon, does not access the item.

@ema2159 maybe you can provide some insights on this one. I'll try to investigate this later.

**Comment by JesusMtnez** [comment]
This is the result when the cursor is just before `~/.emacs.d` project icon, and I try to access the project using `RET` key.
![screenshot_2019-05-22_11-12-53](https://user-images.githubusercontent.com/8639179/58162502-97730100-7c82-11e9-877b-8ded07fd674b.png)

**Comment by ema2159** [comment]
Yes I'm aware of this problem. I've been navigating with tab meanwhile so the cursor falls directly in the text but I'll try to figure whats wrong and fix it!

**Comment by seagle0128** [comment]
I got the ultimate solution, and will submit a PR soon.
