### ISSUE TITLE
Bookmarks and agenda doesn't work

### ISSUE THREAD

**Issue by ema2159** [emacs-dashboard/emacs-dashboard#130]
When a bookmark item is pressed it creates a new file instead of going to the actual bookmarked file. It seems that it's because it's taking the name of the bookmark instead of the path as the argument. When an agenda item is pressed it throws an error. This could be solved just by making agenda items non clickable. @seagle0128 mr. Zhang, please take a look at this when you're able to!

**Comment by ema2159** [comment]
The bookmark problem is probably also in the registers section

**Comment by seagle0128** [comment]
I missed the tests for org and bookmarks. Let me take a look.

**Comment by ema2159** [comment]
Don´t forget to check the registers also!

**Comment by seagle0128** [comment]
The PR #131 is ready.

**Comment by ema2159** [comment]
Nice! This package has improved incredibly in just about 5 days jaja

**Comment by JesusMtnez** [comment]
:clap: Good work!

**Comment by seagle0128** [comment]
> Nice! This package has improved incredibly in just about 5 days jaja

Yep! Amazing. While I was developing this feature in `Centaur Emacs`, I was thinking to merge back to the upstream, not just for Centaur, but worried it was not perfect. I didn't thought you liked it and  moved so fast 😀😀😀
