### ISSUE TITLE
Dashboard is not instantiated if custom bindings are added (using :bind keyword)

### ISSUE THREAD

**Issue by atimchenko92** [emacs-dashboard/emacs-dashboard#132]
Hopefully this is the right place to post the issue. I am using `use-package` to configure the `dashboard` package.
I have some troubles getting `:bind` to work with some custom functions. Here is my snippet:

``` elisp
(use-package dashboard
  :ensure t
  :bind
  (("<f5>" . open-dashboard-buffer)
   :map dashboard-mode-map
   ("l" . play-dashboard-theme))
  :config
  ;; Functions
  (defun play-dashboard-theme ()
    "Plays the dashboard theme"
    (interactive)
    (my/play-media "~/.emacs.d/dashboard/theme.mp3" t))

  (defun open-dashboard-buffer ()
    "Returns the dashboard buffer, if exists"
    (interactive)
    (switch-to-buffer "*dashboard*"))

  (dashboard-setup-startup-hook)
  :custom
  (initial-buffer-choice t)
  (dashboard-items '((recents  . 5)
                     (bookmarks . 5)
                     (projects . 5)
                     (agenda . 5))))
```
With the :bind section active the whole dashboard will not be configured or instantiated. I have already tried placing the function declaration in :init, :config. I even tried using :after keyword. 
Interesting fact is, the binding seem to be configured right, but again, there is no dashboard-buffer created.

**Comment by vxid** [comment]
This may be due to use-package rather than dashboard.
I just noticed the same behavior with mu4e.
