### ISSUE TITLE
Error after updating to version `20190602.1524`.

### ISSUE THREAD

**Issue by jcs090218** [emacs-dashboard/emacs-dashboard#140]
I got an error showing `void-function all-the-icon-fileicon` at the startup. I personally don't use `all-the-icon` package, can you make it compatible so the user can choose what style they want to use? Thank you!

**Edit:** I think the error starts after this PR #137.

**Comment by JesusMtnez** [comment]
@jcs090218 could you please try this branch: https://github.com/emacs-dashboard/emacs-dashboard/tree/fix/do-not-require-all-the-icons

In #141 is the PR that I think would solve this issue. Let me know if it worked for you :wink:

**Comment by jcs090218** [comment]
@JesusMtnez Great! This solved the issue! Thanks for your effort. :D

**Comment by jcs090218** [comment]
I should keep this issue remains opened until the branch `do-not-require-all-the-icons` is merged. Feel free to close it after merging it!

**Comment by JesusMtnez** [comment]
:smiley: I'm glad to hear it works!! I'll merge the PR then :shipit:
