### ISSUE TITLE
7 day agenda view

### ISSUE THREAD

**Issue by miwinning** [emacs-dashboard/emacs-dashboard#146]
Using (setq show-week-agenda-p t) for the 7 day agenda view does not work with (setq dashboard-set-heading-icons t).

It causes an error:- "Wrong type argument: char-or-string-p, nil"

This happens when run in GUI but not with emacs -nw

**Comment by ema2159** [comment]
I think we had this problem previosly or a similar bug, I'll try to see what's going on

**Comment by alecvn** [comment]
Can confirm I have the same problem.  Is there any solution for this yet?

**Comment by JesusMtnez** [comment]
Could you confirm #173 fixed the problem? I'm not an org-agenda user :sweat:

**Comment by miwinning** [comment]
Confirmed fix works

**Comment by JesusMtnez** [comment]
Thank you @DuCorey for the fix
Thank you @miwinning for the confirmation!

Great job!
