### ISSUE TITLE
Could it be possible to put navigator buttons on different lines?

### ISSUE THREAD

**Issue by snackon** [emacs-dashboard/emacs-dashboard#148]
Something like:

```
[button] [button] [button]
     [button] [button]
```
instead of:

```
[button] [button] [button] [button] [button]
```

**Comment by ema2159** [comment]
Not as it is right now. It's a possible future enhancement though.

**Comment by seagle0128** [comment]
I have some ideas to implement that, but it needs some time.

**Comment by ema2159** [comment]
> I have some ideas to implement that, but it needs some time.

Not much it seems jaja, its done a ready to be merged.

**Comment by seagle0128** [comment]
> Not much it seems jaja, its done and ready to be merged.

Yeah, I got a simple but perfect solution, so it doesn't take as long as expected.
