### ISSUE TITLE
Missing required library: 'seq'

### ISSUE THREAD

**Issue by Zzull** [emacs-dashboard/emacs-dashboard#152]
When loading the dashboard, I end up with the following error:
`dashboard-insert-startupify-lists: Symbol’s function definition is void: seq-take`

This is not a big deal since you just have to require it before to make it all work but probably still worth mentioning

**Comment by JesusMtnez** [comment]
Thanks for the tip @Zzull ! I didn't notice that. I'll add the `require` statement.

**Comment by Luis-Henriquez-Perez** [comment]
You only use `seq-take` one time. It's better just to take the elements manually than to load a whole library for just one `seq-take` use. I think it's important for dashboard to be as fast as possible.

**Comment by JesusMtnez** [comment]
@Luis-Henriquez-Perez @Zzull Please, send your :+1: if you agree with https://github.com/emacs-dashboard/emacs-dashboard/pull/161
