### ISSUE TITLE
Allow custom ASCII startup banner too, not only PNG

### ISSUE THREAD

**Issue by andrewbanchich** [emacs-dashboard/emacs-dashboard#153]
I see from the README: `;; 1, 2 or 3 which displays one of the text banners` but how can I add my own?

**Comment by JesusMtnez** [comment]
As far as I know, you would need to added inside the package `banner` folder: https://github.com/emacs-dashboard/emacs-dashboard/tree/master/banners

Maybe a new feature request could be passing the path to a `png` file or `txt` file and handle those cases, since right now it only supports `png` files when passing a path as parameter for `dashboard-startup-banner`.

**Comment by andrewbanchich** [comment]
Should I open a new feature request issue for this then?

**Comment by jcs090218** [comment]
Would it be easier to just have a variable that point to the path of the text file?

**Comment by JesusMtnez** [comment]
> Should I open a new feature request issue for this then?

Let's keep these issue to track that feature. I'll rename it.

> Would it be easier to just have a variable that point to the path of the text file?

We could use the same variable to point to the banner we want to use, and make a logic so it could use both types correctly. It shouldn't be difficult. I'll try to work on that when I get some time :sweat:

**Comment by krzkrzkrz** [comment]
Would like this too. Any updates here?

**Comment by Hkyx** [comment]
you can create a 4.txt and put your ascii in my case it work.

**Comment by jcs090218** [comment]
> you can create a 4.txt and put your ascii in my case it work.

I think replacing the current path is a work around. But it would be great we can point to the file directly! 😄

**Comment by Hkyx** [comment]
yeah but I think it's probably not the most important think, like I got a good config file and if I save it and refresh dashboarfd all works, If I close/open emacs, dashboard use only the half of the config file. so a txt file to create is a little think ;p

**Comment by GiantToast** [comment]
Hey guys, I wanted this too and stumbled upon this issue.
I ended up solving it by creating a banners folder in my `.emacs.d` folder, in which I created a custom `4.txt` banner.
Then I modified my dashboard elisp to be the following:
```elisp
(setq user-banners-dir (concat user-emacs-directory (convert-standard-filename "banners/")))

(defun install-banners ()
  "Copy all files under under banners directory to dashboard banners directory"
  (when (boundp 'dashboard-banners-directory)
    (copy-directory user-banners-dir dashboard-banners-directory nil nil t)))

(use-package page-break-lines
  :ensure t)

(use-package dashboard
  :ensure t
  :after (page-break-lines)
  :config
  (install-banners)
  (setq dashboard-banner-logo-title "")
  (setq dashboard-startup-banner 4)
  (setq dashboard-center-content t)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-items '((recents . 5)
                          (projects . 5)))
  (dashboard-setup-startup-hook))
```
Hope this helps!

**Comment by jcs090218** [comment]
@GiantToast Nice work around! 👍

**Comment by jcs090218** [comment]
This is implemented by #246. Close this now! 😄

**Comment by rstcruzo** [comment]
@jcs090218 I am getting `could not find banner "~/banner.txt", use default instead`. Running `(file-exists-p "~/banner.txt")` manually returns true correctly. Not sure what's causing this.

**Comment by rstcruzo** [comment]
It is because of this https://github.com/emacs-dashboard/emacs-dashboard/commit/44868578ead314be9f4164f39d3d15470fcd4601 .

Why is it not allowed to use `.txt` when not inside terminal?

**Comment by jcs090218** [comment]
I think is a logical error. I have made a PR in #260 to fix this issue.
