### ISSUE TITLE
Dashboard is "prog-mode"?

### ISSUE THREAD

**Issue by ianpan870102** [emacs-dashboard/emacs-dashboard#155]
One thing that's been bothering me is that I'm trying to lazy load some packages that I added hook to prog-mode. But they seem to always be activated when I start up with Dashboard. Is Dashboard using prog-mode?

**Comment by JesusMtnez** [comment]
@ianpan870102 My common sense tells me it should not use `prog-mode`... But I can not assure you 100% it does not use it. I'll try to investigate :thinking:

BTW, could you share you `emacs-dashboard` setup code? Maybe there is something else requiring / using `prog-mode`. Just in case :smile:

**Comment by ianpan870102** [comment]
Sure @JesusMtnez , my Dashboard set-up code is just these few lines:

 ```
 (use-package dashboard
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-startup-banner 'logo
          dashboard-banner-logo-title "Welcome to Emacs. Happy Hacking!"
          dashboard-items nil
          dashboard-set-footer nil))
```

**Comment by jcs090218** [comment]
I think the issue can be closed since dashboard is no longer derived from `prog-mode`.

**Comment by JesusMtnez** [comment]
Thank you @jcs090218 @ianpan870102
