### ISSUE TITLE
Dashboard does not start correctly

### ISSUE THREAD

**Issue by linwaytin** [emacs-dashboard/emacs-dashboard#156]
My dashboard is started without dashboard-mode enabled. The major mode is fundamental. 
It still shows the recent files, but the keybinding and page-break-line do not work.
With `M-X dashboard-mode`, everything works well.

Does anybody has the same problem?

**Comment by JesusMtnez** [comment]
@linwaytin Could you please share you configuration?

**Comment by laralex** [comment]
I encountered this one too, when tried to apply icons for widgets
``` elisp
(use-package dashboard
  :ensure t
  :config
  (progn (dashboard-setup-startup-hook)
         (setq
               dashboard-startup-banner 'logo
               dashboard-center-content nil
               dashboard-items '((recents  . 5)
                                 (projects . 5)
                                 (bookmarks . 10)
                                 (registers . 5)
                                 (agenda . 10))
               dashboard-set-navigator t 
               dashboard-set-init-info t
               dashboard-set-footer nil
               dashboard-set-heading-icons t
               dashboard-set-file-icons t)
         (dashboard-modify-heading-icons '((recents . "clock")
                                           (bookmarks . "bookmark")
                                           (projects . "file-directory")
                                           (agenda . "bell")
                                           (registers . "location")))))
```

Without lines 
```elisp
dashboard-set-heading-icons t
dashboard-set-file-icons t
```
Everything is fine, though without icons aswell
As mentioned, `M-x dashboard-mode` fixes the problem, but it's inconvenient

>

**Comment by linwaytin** [comment]
Hi,

It seems the problem has been fixed.
This morning I started emacs and everything looks fine.

This is my setup for dashboard.

```elisp
(use-package dashboard
  :ensure t
  :config
  (setq show-week-agenda-p t)
  (setq dashboard-items '((recents . 15) (agenda . 5)))
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-startup-banner 3)
  (dashboard-setup-startup-hook)
  )
```

I don't need to do `dashboard-mode` manually.

**Comment by laralex** [comment]
It turned out that `all-the-icons` is missing reference on actually existing icon ["bell"](https://octicons.github.com/icon/bell/) from `octicons`. Trying to use it in `dashboard` caused glitch. Of course it's not a package's problem, but error checking would be appreciated (skipping invalid icons instead of breaking whole buffer) #

**Comment by lckarssen** [comment]
I used to be bitten by this issue as well. However, when I enabled `(setq dashboard-set-file-icons t)` today, all was fine again. I guess the fix has been implemented in `all-the-icons`. I think this issue can be closed.

**Comment by jcs090218** [comment]
Ah. Good to know! Thanks for notifying us! :)
