### ISSUE TITLE
Invalid face attribute :inherit (quote font-lock-keyword-face)

### ISSUE THREAD

**Issue by ema2159** [emacs-dashboard/emacs-dashboard#163]
I am getting that error and I think it's being caused by Dashboard. Does anybody else has this problem?

**Comment by ema2159** [comment]
It seems it's because of the navigator,  do you know something about this error @seagle0128? or are you having it?

**Comment by ema2159** [comment]
Nah, forget it, It was just that I was putting an unnecessary quote in front of the navigator elements faces, it  still worked for some reason but showed those errors. Removing it removes the errors.

**Comment by JesusMtnez** [comment]
Glad to see it solves itself :smile:
