### ISSUE TITLE
Always prompting whether to save dashboard buffer

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [emacs-dashboard/emacs-dashboard#174]
Before quitting emacs  I'm prompted like to save the dashboard buffer. I'm not sure why this is happening. It shouldn't because `*dashboard*` is not a file buffer. Anyway I added this line in the `with-current-buffer` block in `dashboard-insert-startupify-lists`.

```elisp
(set-buffer-modified-p nil)
```

**Comment by JesusMtnez** [comment]
@Luis-Henriquez-Perez I've been trying to reproduce the error, without luck :worried: . Could you share your configuration?

**Comment by Luis-Henriquez-Perez** [comment]
Ok. [This is my configuration](https://github.com/Luis-Henriquez-Perez/.emacs.d/tree/no-use-package). You should just be able to just download and and run init.el to set it up. The buffer modified thing is still happening (I just checked). I'll help you out and try harder to debug it today. It's probably some default variable I'm setting.

**Comment by Luis-Henriquez-Perez** [comment]
I figured it out. Turns out it was my own fault. I used `initial-buffer-choice` to switch to the dashboard, but instead of giving it a buffer I gave it the buffer name as a string, "*dashboard*". In `command-line-1`, this would call `find-file-no-select` which cause dashboard to be considered a file buffer (even though it didn't point to a file).
