### ISSUE TITLE
Some places not using dashboard-buffer-name

### ISSUE THREAD

**Issue by vermiculus** [emacs-dashboard/emacs-dashboard#176]
https://github.com/emacs-dashboard/emacs-dashboard/blob/f76be664ef3e890de03816fd8a2f7e3f74f04982/dashboard.el#L250

https://github.com/emacs-dashboard/emacs-dashboard/blob/f76be664ef3e890de03816fd8a2f7e3f74f04982/dashboard-widgets.el#L255

this is causing problems when customizing the dashboard buffer name -- specifically, a buffer `*dashboard*` still gets created, but is mostly empty (save a few `^L`s).

**Comment by jcs090218** [comment]
This is completed by eca733a829c5b37ae770a0c881b4c50f7dd646c0 and 02cf7b871c822461ca9063505a3de6a0f79499af.
