### ISSUE TITLE
Dashboard PNG conflicts with Solaire mode background

### ISSUE THREAD

**Issue by ianpan870102** [emacs-dashboard/emacs-dashboard#179]
This isn't that big of an issue, but dashboard fails to take into account the influence it inherits from solaire mode, considering solaire a popular package. **Notice the lighter square background around the Emacs logo**. This happens on all themes. Attached are screenshots of **Zenburn** and **Solarized Dark** for your reference.

<img width="645" alt="Screenshot 2019-07-22 at 10 29 18 AM" src="https://user-images.githubusercontent.com/36686900/61602336-b1719580-ac6b-11e9-92eb-81215b59891f.png">

<img width="813" alt="Screenshot 2019-07-22 at 10 28 41 AM" src="https://user-images.githubusercontent.com/36686900/61602352-b8000d00-ac6b-11e9-8912-aad65db7d391.png">

**Comment by ema2159** [comment]
Hi again Ian jaja. I think this problem occurs only in Mac. I know @seagle0128 had this problem before, so maybe he could tell you how to solve it

**Comment by seagle0128** [comment]
Yep, I have the same issue on macOS, only with emacs-plus. It's fine with vanilla Emacs 26.2 for me.

**Comment by ianpan870102** [comment]
I see. I'm indeed running emacs-plus 27.0.50

**Comment by seagle0128** [comment]
I mean it may be an issue with emacs-plus.
Try `C-h C-a` to check the logo. I think you will observe the same issue.

![image](https://user-images.githubusercontent.com/140797/61614951-7ab17480-ac97-11e9-9fee-7d6b3a6a061e.png)

**Comment by ianpan870102** [comment]
True, you're right. Since it's not actionable here in this repo, I'll close the issue.

**Comment by seagle0128** [comment]
I think you can file an issue in `emacs-plus` repo.

**Comment by Hxppdv** [comment]
![](https://user-images.githubusercontent.com/17672838/128632318-c9f652d0-19f3-422d-9eb4-8df425fd43d6.png)
The problem still exists on windows. 
vanilla Emacs 27.2

**Comment by jcs090218** [comment]
> The problem still exists on windows. 
> 
> vanilla Emacs 27.2

Try other Windows build, I can confirmed that some Windows build would still have this issue.

**Comment by seagle0128** [comment]
I think it's related to imagemagick lib. No issue without imagemagick.

**Comment by Hxppdv** [comment]
> 
> 
> I think it's related to imagemagick lib. No issue without imagemagick.

I dont think imagemagick is supported in official Emacs build for windows.

**Comment by Hxppdv** [comment]
> 
> 
> > The problem still exists on windows.
> > vanilla Emacs 27.2
> 
> Try other Windows build, I can confirmed that some Windows build would still have this issue.


I have tried many other builds and still have the same problem.

**Comment by jcs090218** [comment]
> I have tried many other builds and still have the same problem.

I am also on Windows with this https://ftp.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.2-x86_64-installer.exe build. Weird that I am not able to reproduce this behaviour...

**Comment by Hxppdv** [comment]
> I am also on Windows with this [ftp.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.2-x86_64-installer.exe](https://ftp.gnu.org/gnu/emacs/windows/emacs-27/emacs-27.2-x86_64-installer.exe) build. Weird that I am not able to reproduce this behaviour...

This is really weird, I'm using the same build as you and I tried to have only dashboard doom-themes and solaire-mode installed and still have this problem.

**Comment by Hxppdv** [comment]
![](https://user-images.githubusercontent.com/17672838/128642746-5564dd3b-c905-4528-8a9d-916c57ac7e43.gif)
The problem comes after I turn on solaire-mode in any way. Another strange thing is that when I change the size of the frame, it goes back to normal.

**Comment by seagle0128** [comment]
@Hxppdv so the solution is disabling `solarire-mode` in dashbaord buffer?

**Comment by Hxppdv** [comment]
@seagle0128 I tried your Centaur Emacs before, and I don't know what you did to make the display normal, but once you turn off solaire-mode in the dashboard buffer and turn it on again, the same problem occurs.

![](https://user-images.githubusercontent.com/17672838/128733474-625fa2fb-9966-4e05-8a54-eaa535ecb471.gif)

**Comment by seagle0128** [comment]
@Hxppdv No issue on macOS and Linux. I am using emacs-plus without imagemagick.

**Comment by Hxppdv** [comment]
> 
> 
> @Hxppdv No issue on macOS and Linux. I am using emacs-plus without imagemagick.

I also have problems on wsl
I'm using vanilla emacs 27.2 on windows 10. Maybe this problem will only exist on windows.
