### ISSUE TITLE
Not an issue, just

### ISSUE THREAD

**Issue by CarlQLange** [emacs-dashboard/emacs-dashboard#18]
I was the person who put in the original pull request -> https://github.com/syl20bnr/spacemacs/pull/977 <- for the startup lists.

It's awesome to see this!

👍 👍 👍

**Comment by rakanalh** [comment]
WoW i am glad this got your attention! 

First of all, thank you for making this and am glad that i finally know whose code am stealing :p I actually learned elisp when creating this package and playing around with the code.

It would be nice if we can work together to bring this forward. This has seen quite some activity from the non-spacemacs users so your experience could bring some nice features into this package. I can give you push access as you probably know the code better than i do :)

Nevertheless, thanks again!

**Comment by CarlQLange** [comment]
Haha, this was also my first foray into elisp! I still use spacemacs but haven't really built anything else since this - and it was almost two years ago now! I don't think there's much I could do to help you :) Just wanted to drop by and say how cool this is!
