### ISSUE TITLE
dashboard-{next,prev}-line on by default

### ISSUE THREAD

**Issue by fredefox** [emacs-dashboard/emacs-dashboard#187]
I propose to add

```
(add-hook 'dashboard-mode-hook
          (lambda ()
             (local-set-key "n" 'dashboard-next-line)
             (local-set-key "p" 'dashboard-previous-line)))
```

As a default for `dashboard-mode`. I realize that I can just add this to my own config file (and I have). I just thought other people might be interested as well. This is in line with Buffer Menu.

**Comment by jcs090218** [comment]
Good idea! I think there is no harm for this to implement. If anyone in the community wants this; and please leave a comment to this thread!

Thank you all!

**Comment by rudi** [comment]
I was thinking the same, but `p` is already bound and jumps to the projects widget.

**Comment by jcs090218** [comment]
Yeah, I think @rudi has a good point here. I guess I will close this issue for now. 

@fredefox Feel free to reopen this if you find out useful.

**Comment by fredefox** [comment]
Perhaps `P` could be used for the "jump to projects" widget.

**Comment by rudi** [comment]
How about j/k for up/down, for us old nethack players?  These keys are currently not used for quick access to any section
