### ISSUE TITLE
[Question] create image

### ISSUE THREAD

**Issue by seagle0128** [emacs-dashboard/emacs-dashboard#203]
Hi,

I open this issue just for inquiry of creating the banner image. I noticed if `imagemagick` is available, the image will be created with `'imagemagick` type, which will cause the different background in my env as below.

![image](https://user-images.githubusercontent.com/140797/71514108-0348d680-2902-11ea-95c4-219b038468fa.png)

But if just using `(create-image banner)`, all look fine. My I know why handle like this?

https://github.com/emacs-dashboard/emacs-dashboard/blob/87779af059b33559c88596793cc55504c418fd32/dashboard-widgets.el#L357

**Comment by JesusMtnez** [comment]
Not sure why it is handled using `imagemagick`. I think we could change that to `create-image` and see how it works :thinking:

**Comment by seagle0128** [comment]
Since Emacs27, `imagemagick` is not necessary. Emacs use the built-in API to handle images.

https://github.com/emacs-mirror/emacs/blob/emacs-27/etc/NEWS

> ** Emacs no longer defaults to using ImageMagick to display images.
This is due to security and stability concerns with ImageMagick.  To
override the default, use 'configure --with-imagemagick'.

**Comment by jcs090218** [comment]
I don't have old Emacs version on my machine. If `create-image` just work, I guess we can just use that and not even think about `imagemagick` support? 😕

**Comment by seagle0128** [comment]
@jcs090218 I think so.

**Comment by jcs090218** [comment]
> @jcs090218 I think so.

@JesusMtnez What do you think about this?

**Comment by JesusMtnez** [comment]
I think we could refactor image handling to  use `create-image` that will only use `imagemagick` if it is an available feature in Emacs. I took inspiration from `telega.el` but it should be pretty easy to refactor...

**Comment by seagle0128** [comment]
It doesn't exist any more. Closing it.
