### ISSUE TITLE
Optional activation of dashboard

### ISSUE THREAD

**Issue by csevast** [emacs-dashboard/emacs-dashboard#208]
I want to adapt my `init.el` in a way the `dashboard` to start optionally. I want to have different Emacs instances, with or without `dashboard`, using the same initialization file. Unfortunately, when the `dashboard-setup-startup-hook` is evaluated after Emacs' start-up nothing happens. Is there any `dashboard` function to start displaying it's buffer after Emacs' start-up?

**Comment by jcs090218** [comment]
Try this.

```el
(defun my--startup-dashboard()
  (switch-to-buffer "*dashboard*")
  (goto-char (point-min))
  (redisplay))
```

**Comment by jcs090218** [comment]
@csevast Does the code work for you? Thanks!

**Comment by jcs090218** [comment]
I think this is resolved? Close this issue now! :)
