### ISSUE TITLE
Support for counsel-projectile

### ISSUE THREAD

**Issue by yurikoif** [emacs-dashboard/emacs-dashboard#215]
Dashboard is amazing, but it supports projectile rather than its variation counsel-projectile.
When I try to open a project, the file list is shown in a raw projectile-style single line mini-buffer, but what I want is a counsel(ivy)-style mini-buffer.

**Comment by jsigman** [comment]
Also came here looking for this!

**Comment by mohkale** [comment]
not sure what you mean? Could you post a screenshot of what you'd like to be shown and what is actually shown?

**Comment by yurikoif** [comment]
> not sure what you mean? Could you post a screenshot of what you'd like to be shown and what is actually shown?

Thank you for replying.
Selection minibuffer in cousel-projectile looks like this:
![Screenshot from 2020-06-25 05-19-44 (1)](https://user-images.githubusercontent.com/10281921/85693651-6d211d80-b6a4-11ea-9ab0-2e9496066189.png)
while dashboard uses original ido style selection minibuffer:
`[project-name] Find file: {a | b | c | ...}`

**Comment by mohkale** [comment]
which command are you running to get a list of projects to switch to?

These are all the commands my dashboard install has available:

```
    dashboard-mode
    dashboard-return
    dashboard-next-line
    dashboard-a-shortcut
    dashboard-p-shortcut
    dashboard-r-shortcut
    dashboard-next-section
    dashboard-previous-line
    dashboard-refresh-buffer
    dashboard-previous-section
    dashboard-insert-startupify-lists
```

**Comment by ricardoricho** [comment]
Hi, I've just submitted a PR to custom the function that I use with [perp-projectile](https://github.com/bbatsov/persp-projectile).
While I was testing I found `(setq projectile-completion-system 'ivy)` tells projectile always use ivy.

**Comment by jsigman** [comment]
@ricardoricho When I tested this with dashboard it doesn't do anything when I select a project. Thanks though

**Comment by jacksonbenete** [comment]
@jsigman , @ricardoricho solution worked for me.

![image](https://user-images.githubusercontent.com/2954722/91771434-625d9a00-ebb9-11ea-9328-43d3afc7381f.png)

Maybe Counsel needs any special call/require that you're not using?
I will show you the relevant conf in my init.el, maybe it will help:

```lisp
;; Ivy/Counsel
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)

;; Ido
(require 'ido)
(setq ido-enable-flex-matching t)
(setq ido-everywhere t)
(ido-mode 1)

;; Ivy Posframe
(add-to-list 'load-path "~/.emacs.d/ivy-posframe")
(require 'posframe)
(require 'ivy-posframe)
(setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display)))
(setq ivy-posframe-display-functions-alist '((t . ivy-posframe-display-at-window-center)))
(ivy-posframe-mode 1)

;; Projectile
(projectile-mode +1)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(setq projectile-completion-system 'ivy)
```

That's all the conf related to "find" I have. I didn't tested removing one or another to see what might break the way it's working right now, so I paste everything so you can try paste in your conf or select what may work.

**Comment by jcs090218** [comment]
I think `(setq projectile-completion-system 'ivy)` does the trick?

@yurikoif Does @ricardoricho answer work for you? Thanks!

**Comment by jsigman** [comment]
Doesn't work when I use `(setq projectile-completion-system 'ivy)`.  I've been playing with `selectrum`, as well, and this still doesn't work with the default completion system +  `selectrum` either.

**Comment by RJSent** [comment]
I found `(setq projectile-completion-system 'ivy)` worked for me.
