### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by JesusMtnez** [emacs-dashboard/emacs-dashboard#217]
Current CI does not work:

- [ ] `let-alist` dependency necessary for emacs 25.
- [ ] `package-lint` has been integrated in `elisp-lint` and it is throwing some errors. It has been disabled for now.
- [ ] Some linting erros

**Comment by jcs090218** [comment]
I think is related to this?

[package-lint/issues/154](https://github.com/purcell/package-lint/issues/154)
