### ISSUE TITLE
dashboard-footer is not respected

### ISSUE THREAD

**Issue by seagle0128** [emacs-dashboard/emacs-dashboard#219]
I found `dashboard-footer` is not respected now. Whatever I set it, it won't be displayed, while other random messages instead.

**Comment by jcs090218** [comment]
Due to this commit [198daac](https://github.com/emacs-dashboard/emacs-dashboard/commit/198daacdab2bf410b277dee4995568633b105845). You can simple just change the value of `dashboard-footer-messages` variable to ensure the footer you want to be displayed.

**Comment by jcs090218** [comment]
@JesusMtnez You might want to close this too?

**Comment by seagle0128** [comment]
Thank you for updating documentation!
