### ISSUE TITLE
How to reopen the Dashboard

### ISSUE THREAD

**Issue by jacksonbenete** [emacs-dashboard/emacs-dashboard#236]
Hello there,
I'm pretty new to Emacs and to Lisp, so I don't have much experience. I've installed dashboard in my custom Emacs and I would like to be able to "reopen" the dashboard, like if the dashboard buffer is killed or closed I could call it with a shortcut.

That's what I've tried:
```lisp
;; Remap Open Dashboard
(defun create-dashboard-buffer nil
  "Create a dashboard buffer"
  (interactive)
  (switch-to-buffer (get-buffer-create "*dashboard*"))
  (lisp-interaction-mode))
(global-set-key (kbd "C-S-d") 'create-dashboard-buffer)
```

The problem is that, if the dashboard is "hidden" (I'm in another buffer), the get-buffer-create gives me a broken dashboard where it doesn't works.
If the dashboard is closed (I've killed it with C-x k), then I only receive an empty-buffer called *dashboard*. That's pretty obvious now that I've tried it, but I thought that *dashboard* was some kind of reserved word once the package was installed. lol

There is a way to "create" a "dashboard" like if I was restarting the Emacs and attach it to a keybinding?

**Comment by jacksonbenete** [comment]
I'm a little confused because I'm learning Racket and not Emacs Lisp, so I'm not sure how to do some things yet.
This is what I thought so far, but the get-buffer doesn't seems to return the name and dashboard-setup-startup-hook looks like 
isn't the correct function to call in this point because it doesn't work.

```lisp
;; Remap Open Dashboard
(require 'dashboard)
(dashboard-setup-startup-hook)

(defun call-dashboard nil
  (interactive)
  (let ((buffer-exists (get-buffer "*dashboard*")))
    (if (buffer-exists)
	'dashboard-refresh-buffer
      'dashboard-setup-startup-hook)
  ))

(global-set-key (kbd "C-S-d") 'call-dashboard)
```

Maybe I should use buffer-live-p, or maybe there is a way to do something like:

```lisp
(defun call-dashboard nil
  (interactive)
  (if ('dashboard-refresh-buffer) nil 'dashboard-setup-startup-hook))
```

**Comment by jcs090218** [comment]
Try the code below.

```el
(defun my-dashbaord ()
  "Jump to the dashboard buffer, if doesn't exists create one."
  (interactive)
  (switch-to-buffer dashboard-buffer-name)
  (dashboard-mode)
  (dashboard-insert-startupify-lists))
```

Mainly, you just have to call function `dashboard-insert-startupify-lists`. Then it should do the trick.

**Comment by jcs090218** [comment]
I think this is duplicate to #208. Mark duplicate now.

**Comment by jacksonbenete** [comment]
Kinda of, if the dashboard doesn't exists (like, no `(dashboard-setup-startup-hook)` in my init.el) it will create dashboard just fine in the first time, but if the dashboard was killed it will just jump to an empty buffer and don't initialize dashboard again.

**Comment by jacksonbenete** [comment]
Ok, I get it, in fact it need a refresh, so the following will work just right.

```lisp
;; Remap Open Dashboard
(defun new-dashboard ()
  "Jump to the dashboard buffer, if doesn't exists create one."
  (interactive)
  (switch-to-buffer dashboard-buffer-name)
  (dashboard-mode)
  (dashboard-insert-startupify-lists)
  (dashboard-refresh-buffer))
(global-set-key (kbd "<f1>") 'new-dashboard)
```

Thank you very much!
I will Close the issue if you don't mind.
