### ISSUE TITLE
More maintainers?

### ISSUE THREAD

**Issue by jcs090218** [emacs-dashboard/emacs-dashboard#241]
Hi, I use this package everyday for my programming life. 

I wonder if I can co-maintain this package? Let me know what the team thinks! Thanks!

Ping @rakanalh @JesusMtnez

**Comment by JesusMtnez** [comment]
:+1: I would really like to have more maintainers in this project. I have not been able to help to maintain this package during this year even if I want to. I would really appreciate the help :clap:

**Comment by jcs090218** [comment]
Awesome! Can you add me to the organization and give me the permission to this repository?

Thanks!

**Comment by JesusMtnez** [comment]
> Awesome! Can you add me to the organization and give me the permission to this repository?

I do not have those permissions. I think @rakanalh is the `owner`

**Comment by jcs090218** [comment]
No problem! :)

We can wait until @rakanalh sees this.

**Comment by rakanalh** [comment]
@JesusMtnez granted you an owner role to the org & invited @jcs090218 to participate.

**Comment by JesusMtnez** [comment]
@rakanalh Thank you! :tada:

**Comment by jcs090218** [comment]
@rakanalh Thank you!

One question here. I received an email " Your invitation to emacs-dashboard has been canceled". 😕

**Comment by JesusMtnez** [comment]
@jcs090218 inviting you again :wink:

**Comment by jcs090218** [comment]
@JesusMtnez Got it!

Can you invite me to the organization. I feel like is a bit easier for me to navigate to the repository.

Anyway, I am closing this now! Thank you! 👍

**Comment by jcs090218** [comment]
@JesusMtnez You there? Thank you!

**Comment by JesusMtnez** [comment]
Do not worry, as soon as I can get to the computer, I will invite you to the org too. 🤩👍

**Comment by jcs090218** [comment]
Sorry for bothering you! Just want to ensure this before I forget about it. Thanks! 😄

**Comment by JesusMtnez** [comment]
Should be done now! :smile:
