### ISSUE TITLE
Move CI to GitHub Actions

### ISSUE THREAD

**Issue by JesusMtnez** [emacs-dashboard/emacs-dashboard#244]
We could migrate (and improve at some point) the package CI to GitHub Actions like: https://github.com/purcell/setup-emacs

**Comment by jcs090218** [comment]
This would be great! I have `purcell@setup-emacs`  working on my config; see https://github.com/jcs090218/jcs-emacs. If you want to working windows you can use mine setup emacs for Windows here -> https://github.com/jcs090218/setup-emacs-windows.

These are the `.yml` files for both CI tests.

* https://github.com/jcs090218/jcs-emacs/blob/master/.github/workflows/ci_windows.yml
* https://github.com/jcs090218/jcs-emacs/blob/master/.github/workflows/ci_nix.yml

**Comment by JesusMtnez** [comment]
Nice!!!! :clap: :clap: I will try to take a look at this, really interesting having more than Linux validation for the package :eye:
