### ISSUE TITLE
Org Agenda not being highlighted on startup, but when saving the corresponding org file

### ISSUE THREAD

**Issue by sailikk** [emacs-dashboard/emacs-dashboard#264]
1. I open up Emacs, and notice that I don't see the usual highlighting of the keyword NEXT or the text "Pay Credit Card" like they appear in my `school.org` file usually:
![image](https://user-images.githubusercontent.com/46624965/100518467-a253ff00-315f-11eb-91a6-65028ec3f40e.png)
2. (optional): Try to refresh the buffer a few times with `dashboard-refresh-buffer`. Note that nothing changes.
3. I press `a` to get to the agenda section, and point is immediately teleported to the "Pay Credit Card" heading shown here.
4. I get to `school.org` which opens up as a split window on the right
5. I immediately do `delete-window` (bound to `C-x 0` usually)
6. I am back to the `*dashboard*` buffer, and see this (the org heading is now highlighted)
![image](https://user-images.githubusercontent.com/46624965/100518462-9ec07800-315f-11eb-8e01-821a8713493d.png)

I would like the org heading to be highlighted as usual when I start up. Would this be a bug?

Edit: Here is also my `use-package dashboard` block:
```elisp
(use-package dashboard
  :init
  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  :config
  (setq dashboard-startup-banner 'logo)
  (dashboard-setup-startup-hook))
```

**Comment by jcs090218** [comment]
Are you talking about something changes after the recent commits? Can you tell me what version of dashboard are you using? I think the issue appears after this PR here #238?

**Comment by sailikk** [comment]
Sorry for late reply..

My elpa has a directory named dashboard-20201114.928, which should be the most recent MELPA version, right? New to Emacs, so please correct me if I have some misunderstanding. Oh, I think this is somewhat outdated. According to https://melpa.org/#/dashboard 20201207.1445 should be the most recent. What would be a good way to update it for someone using `use-package`? I will try to look this up as well.

I just started using dashboard a couple weeks ago. Also, I tried putting the `use-package dashboard` block as the last thing in my `init.el`, but nothing changes.

**Comment by sailikk** [comment]
Okay, I figured out how to update my elpa directory packages, and everything is up to date now. The same thing is still happening with dashboard unfortunately

**Comment by jcs090218** [comment]
> Regardless, 11/14 seems to be after the PR you mentioned was merged, so would this be a problem?

I am trying to debug here. Not sure what causes this issue. I am assuming PR #238 is the culprit.

> Try require org-agenda before loading dashboard? 😕

Have you tried this? Thanks!

**Comment by sailikk** [comment]
Sorry for the confusion.
I will detail the facts once more:
This is what I see when I do `M-x list-packages`:
```
  dashboard          20201209.1003 installed             A startup screen extracted from Spacemacs
```
I just upgraded, and the latest version (from today) is installed. Therefore, I must already have the version using the PR you mentioned. Hope this clarifies where I am with regards to PR #238.

> Try require org-agenda before loading dashboard? 😕

I am a beginner at Emacs, so I am not 100% sure what you mean here either. I use `use-package`, but not  `require`.

To preface, I am not using the `:after` option that comes with `use-package`. In light of this: I have my `init.el` set up such that `(use-package org...)` occurs before `(use-package dashboard ...)`. I think this means that I load `org-agenda` before `dashboard`. I hope that this answers your question. I never have a `(use-package org-agenda ...)` block because that comes with `org` itself, I think.

More precisely, a truncated `init.el`:
```
...
;; initial stuff
...

;; Org mode configuration
(use-package org
  :bind
  (("C-c l" . org-store-link)
   ("C-c a" . org-agenda)
   ("C-c c" . org-capture))
  :config
  (setq org-agenda-window-setup 'other-window
        org-agenda-restore-windows-after-quit t
        org-agenda-show-future-repeats nil))
(require 'org-mouse)

(use-package org-journal
  :ensure t
  :defer t
  :config
  (setq org-journal-dir "~/org/journal/"
        org-journal-date-format "%A, %d %B %Y"
        org-journal-time-format "%I:%M %p"))
(global-set-key (kbd "C-c j") 'org-journal-new-entry)

....
;; many lines of other stuff
....

(use-package dashboard
  :init
  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  :config
  (setq dashboard-startup-banner 'logo)
  (dashboard-setup-startup-hook))
````

**Comment by jcs090218** [comment]
> I am a beginner at Emacs, so I am not 100% sure what you mean here either. I use use-package, but not require.

No worries! I mean in the previous PR #238 it was requiring `org-agenda` like `(require 'org-agenda)`. I am guessing that is why this isn't working at the very beginning of the dashboard buffer. So maybe try the following,

```el
(use-package dashboard
  :config
  (require 'org-agenda))
```

**Comment by sailikk** [comment]
Just putting:
```
(use-package dashboard
  :config
  (require 'org-agenda))
```
just gives me the `*scratch*` buffer when starting up.

Doing this:
```
(use-package dashboard
  :init
  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  :config
  (require 'org-agenda))
```

Gives the same behaviour as initially described for this issue unfortunately.

**Comment by jcs090218** [comment]
Sorry for the confusion! I mean you should just have `(require 'org-agenda)` in you `use-package` block! You should keep your original configuration.

**Comment by sailikk** [comment]
Alright. This is my new config:
```
(use-package dashboard
  :init
  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  :config
  (require 'org-agenda)
  (setq dashboard-startup-banner 'logo)
  (dashboard-setup-startup-hook))
```
Same issue happens when starting up Emacs unfortunately.

**Comment by jcs090218** [comment]
@sailikk I think we have the fix from @ricardoricho. Can you please test the latest version? Thanks!

**Comment by sailikk** [comment]
It works! Thanks to both of you. Feel free to close.

**Comment by jcs090218** [comment]
Close this now! Thanks! ;)
