### ISSUE TITLE
the dashboard showing aganda shows all TODO's 

### ISSUE THREAD

**Issue by algon-ns** [emacs-dashboard/emacs-dashboard#266]
My Dashboard shows entries from next year, it seems like the filter do not work fdate/time not i US format.
![emacs-dash](https://user-images.githubusercontent.com/58687687/101221354-d2cbf980-3687-11eb-8c50-61b45485c44b.png)

**Comment by jcs090218** [comment]
I think you are talking about the PR #238? If you want to change the time string try change the variable `dashboard-agenda-time-string-format`. 😕

---

Thanks for reporting this issue to us! 😄

**Comment by algon-ns** [comment]
Sorry, 
the time format is OK (%Y-%m-%d)
I changed (show-....) to (dashboard....)
and I'm running emacs version 28.0.50, and the problem persist

and I didnot understand the answer for #238

**Comment by jcs090218** [comment]
> and I didnot understand the answer for #238

No worries! I was trying to understand the issue here. I guess you are talking about the filter?

I think PR #238 has changed the filtering process to `dashboard-match-agenda-entry`. May be try tweaking the variable? 😕

**Comment by algon-ns** [comment]
Thanks,

the dashboard-match-agenda…æ is nil, any suggestions of other values?

It look like I do not get the latest version of dashboard, I’m using straight.el to get the dashboard, and
I have no ideas how to get  (straight-use package to process all the config parameters

*** Dashboard
:PROPERTIES:
:CUSTOM_ID: Dashboard
:END:
 [[https://github.com/emacs-dashboard/emacs-dashboard][Dashboard]] - A startup dashboard which provides certain information 
             about your recent Emacs activities.
We want a Dashboard, which demand Page Break Line 
#+begin_src emacs-lisp
(straight-use-package '(page-break-lines :type git :flavor melpa :host github :repo "purcell/page-break-lines"))
(setq page-break-lines-lighter " ⩵")
(global-page-break-lines-mode)

(use-package dashboard
  :straight t 
  :diminish
  :bind ("<f2>" . open-dashboard)
  :custom
  (dashboard-banner-logo-title "Open EMACS for a new world...")
  (dashboard-startup-banner "/Users/niels/.emacs.d/images/ohands.png")
  (dashboard-items '( (bookmarks . 6) (agenda . 6)))
  (initial-buffer-choice (lambda () (get-buffer dashboard-buffer-name)))
  (dashboard-set-heading-icons t)
  (dashboard-set-navigator t)
  (dashboard-navigator-buttons
   '(((#("" 0 1
         (rear-nonsticky t display
                         (raise -0.06)
                         font-lock-face
                         (:family "github-octicons" :height 1.32)
                         face
                         (:family "github-octicons" :height 1.32)))
       "ALGON" "Browse ALGON Homepage"
       (lambda
         (&rest _)
         (browse-url "https://algon.dk"))))))
 :custom-face
  (dashboard-banner-logo-title ((t (:family "Love LetterTW" :height 123))))
 :config
  (dashboard-modify-heading-icons '((recents . "file-text")
                                    (bookmarks . "book")))
  (setq dashboard-center-content t)
  (setq dashboard-week-agenda t) )
(dashboard-setup-startup-hook) 

(defun open-dashboard ()
    "Open the *dashboard* buffer and jump to the first widget."
    (interactive)
    (if (get-buffer dashboard-buffer-name)
        (kill-buffer dashboard-buffer-name))
    (dashboard-insert-startupify-lists)
    (switch-to-buffer dashboard-buffer-name)
    (goto-char (point-min))
    (delete-other-windows))

(if nec/measure-time (nec/timer "Dashboard   "))
#+end_src


med venlig hilsen(= With Kind Regards)
Niels
 <applewebdata://33EE3DC6-C647-4DEC-B050-08B4D23616F7>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 2789 niels@algon.dk <mailto:niels@algon.dk>

**Comment by jcs090218** [comment]
@algon-ns Can you test the patch #269 and if it works? Thanks! ;)

**Comment by algon-ns** [comment]
Hello Jen-Chieh,

I’m unsure, where to insert the patch…

If I put it in my initfile after loading dashboard, it comes out with an error:

: Before first headline at position 1 in buffer *scratch*

mvh
Niels
 <applewebdata://D1529CA5-16CB-4EA0-A72C-8BC568D37CCD>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 2789 niels@algon.dk <mailto:niels@algon.dk>

**Comment by jcs090218** [comment]
Hi Niels!

Try evaluate the following code by calling `eval-buffer`! Just paste the code in `*scratch*` buffer and `M-x eval-buffer`.

```el
(defun dashboard-filter-agenda-by-time ()
  "Include entry if it has a schedule-time or deadline-time in the future.
An entry is included if this function returns nil and excluded
if returns a point."
  (let ((schedule-time (org-get-scheduled-time (point)))
        (deadline-time (org-get-deadline-time (point)))
        (due-date (dashboard-due-date-for-agenda)))
    (unless (and (not (org-entry-is-done-p))
                 (or (and schedule-time
                          (org-time-less-p schedule-time due-date))
                     (and deadline-time
                          (org-time-less-p deadline-time due-date))))
      (point))))
```

Let me know if this works! Thanks! 😄

**Comment by algon-ns** [comment]
It works as expected……

how can I put it in?

mvh
Niels
 <applewebdata://E9ACEC66-8FD8-4B28-9491-1D117393017E>
Niels Søndergaard
Mariehøj 236, 2990 Nivå
 <tel:+45 4052 2789>+45 4052 2789 niels@algon.dk <mailto:niels@algon.dk>

**Comment by jcs090218** [comment]
PR #269 is merged! It will be up and running in the latest version of `dashboard`! Thanks!

**Comment by shackra** [comment]
I was having this issue, pulled the new code for this packaged, rebuilt and restarted Emacs and now entries show as expected
