### ISSUE TITLE
Truncate elements

### ISSUE THREAD

**Issue by ema2159** [emacs-dashboard/emacs-dashboard#276]
Hi! I was looking for an option to truncate the dashboard's items since sometimes they became too long. I thought that `dashboard-items-default-length` did that but it is not the case so this could be a nice option to add.

Some inspiration can be taken from https://github.com/seagle0128/doom-modeline since it has several options for displaying files when their paths are too long.

**Comment by jcs090218** [comment]
> Some inspiration can be taken from https://github.com/seagle0128/doom-modeline since it has several options for displaying files when their paths are too long.

Hi! Can you elaborate the feature from [doom-modeline]() about the path too long issue? I don't use this package so I am not very familiar with it.

Anyway, thanks for reporting this issue to us! 😄

**Comment by ema2159** [comment]
doom-modeline's documentation explains it best, so here I attach it:
![image](https://user-images.githubusercontent.com/17773218/102721786-a5c54b00-4305-11eb-965a-98a14571fc41.png)

It would be awesome if something similar could be implemented for Dashboard's elements.

**Comment by ema2159** [comment]
Closed in #279
