### ISSUE TITLE
Remove CircleCI

### ISSUE THREAD

**Issue by jcs090218** [emacs-dashboard/emacs-dashboard#291]
@JesusMtnez I don't think we need CircleCI anymore? 

I don't I have the permission to remove it. Can you remove it for us? Thanks! :)

**Comment by JesusMtnez** [comment]
I will take a look to it. Not sure if I am able to. I'll let you know.

**Comment by jcs090218** [comment]
I have found this article. See if this helps?

https://support.circleci.com/hc/en-us/articles/360021666393-How-to-manually-stop-building-by-removing-your-deploy-key-and-webhook-from-GitHub

**Comment by JesusMtnez** [comment]
I have just removed it.
