### ISSUE TITLE
Logo image not displaying properly

### ISSUE THREAD

**Issue by zamlz** [emacs-dashboard/emacs-dashboard#293]
I'm unable to display the logo image within emacs. Whether it be the built in ones or a custom path.
Here is what I have right now. Inline images do work and was able to get it working in my org files.
All i'm able to see is a small white box.

```elisp
(use-package dashboard
  :ensure t
  :config
  (setq dhasboard-startup-banner 'official)
  (setq dashboard-center-content t)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-set-navigator t)
  (setq dashboard-set-init-info t)
  (setq initial-buffer-choice (lambda() (get-buffer "*dashboard*")))
  (setq dashboard-items '((recents   . 10)
              (bookmarks . 5)
              (projects  . 10)
              (agenda    . 10)
              (registers . 5)))
  (dashboard-modify-heading-icons '((bookmarks . "book")))
  (dashboard-setup-startup-hook))
```

Any help to diagnose whats wrong would be appreciated :)
Currently using `GNU Emacs 27.1`

**Comment by jcs090218** [comment]
Make sure you have `dasboard-startup-banner` and not `dhasboard-startup-banner`.

I don't see any issue from you configuration. This looks strange to me. To better investigate this issue, can you take a screenshot of your screen? Thanks!

**Comment by zamlz** [comment]
Oh I thought I fixed that, sorry that was an old version of the config. But even with the typo fixed, I still only see the white box.
![2021-02-01-085856_784x125_scrot](https://user-images.githubusercontent.com/10750027/106491874-2aaa9500-646c-11eb-98a4-323270e52f98.png)

**Comment by jcs090218** [comment]
Can you try `imagemagick` support? I don't why this is happening...

We already have a check for `imagemagick` and even it doesn't then it should use the built-in version of `insert-image`.

**Comment by zamlz** [comment]
Figured it out, it appears my distributiion's build script for the package was not building emacs with imagemagick support correctly. Just updated my emacs right now and its been fixed!
