### ISSUE TITLE
Silently read org files to add agenda items in Dashboard

### ISSUE THREAD

**Issue by ig-perez** [emacs-dashboard/emacs-dashboard#297]
Hi, thanks for maintaining this package!

I have many org files and when opening Emacs, Dashboard seems to read all of them to find TODOs and add them to the agenda section. The problem with this is that the files are kept open after displaying Dashboard.

Since I use Centaur Tabs I have a lot of tabs for the org files opened by Dashboard. Is this normal behavior? If yes, can it be changed to silent-mode, or closing the org files once read?

Thanks!

**Comment by jcs090218** [comment]
Hi, I am not quite sure the default action for agenda. I think @ricardoricho may know the the answer? :)

**Comment by ricardoricho** [comment]
Hi @ig-perez 
Yes, the normal behavior for org-agenda is to leave the buffers open. Now it will close the "untouched" files.
Thanks.

**Comment by ricardoricho** [comment]
Hi
The issue with this is that if we close all the agenda buffers next time Dashboard is refresh it will take time to open the agenda files again.
The question is when do we close the buffers? If it's only the first time maybe with a hook
```elisp
(add-hook 'dashboard-after-init-hook (lambda () (org-release-buffers org-agenda-new-buffers)))
```
@jcs090218 In the PR buffers are open and close each time the Dashboard buffer is refresh, to keep that behavior  we can add config var or a hook or... maybe advising the correct function will do the job.

**Comment by ig-perez** [comment]
Thank you guys. If you allow me, I'd suggest to use a variable to let Dashboard know if it should keep the files open or close after generating the agenda items.

Perhaps you can add this to the documentation saying that closing the files will increase time when refreshing Dashboard. One question here, does Dashboard auto refresh its contents or that is a user triggered action?

**Comment by jcs090218** [comment]
> @jcs090218 In the PR buffers are open and close each time the Dashboard buffer is refresh, to keep that behavior we can add config var or a hook or... maybe advising the correct function will do the job.

Hmm.. I think adding a config variable would work. It's great to let users decide what's the package's behavior.

> One question here, does Dashboard auto refresh its contents or that is a user triggered action?

You would need to `M-x dashboard-refresh-buffer` to trigger it's action.

**Comment by jcs090218** [comment]
@ig-perez #298 is merged! Can you set variable `dashboard-agenda-release-buffers` to `t` and see if this work for you? Thanks!

**Comment by ig-perez** [comment]
Hi @jcs090218 I just updated `Dashboad` and used the new variable. Everything is working as expected. Thank you very much to both of you.

Have a great day!
