### ISSUE TITLE
Handle bookmarks with no filename

### ISSUE THREAD

**Issue by Stebalien** [emacs-dashboard/emacs-dashboard#308]
`bookmark-get-filename` can fail for some bookmarks (e.g., notmuch, shell, etc.). This package used to handle these bookmarks just fine, but it now fails with `dashboard-shorten-path: Wrong type argument: stringp, nil`.

**Comment by jcs090218** [comment]
Sorry for the inconvenience! 

I have opened the patch in #309 and hopefully it will get merge soon!

**Comment by Stebalien** [comment]
Thanks!
