### ISSUE TITLE
Can content be centered vertically?

### ISSUE THREAD

**Issue by yosevu** [emacs-dashboard/emacs-dashboard#318]
I see that content can be centered horizontally with `(set dashboard-center-content t)`, but is there also a way to center it vertically? I would like to do this because I am setting the startup banner to nil.

**Comment by jcs090218** [comment]
No, there is no such a feature. We are open for PR, feel free to contribute to emacs-dashboard! 😁

**Comment by qkweint** [comment]
What I do is increase the height of the logo with a photo editor which works great.
![image](https://user-images.githubusercontent.com/69873602/166099557-d2cc4f34-e199-4b27-af54-99697aa609a7.png)
540x670

**Comment by pradyungn** [comment]
Would love to see this!

**Comment by cvdub** [comment]
Added a [PR](https://github.com/emacs-dashboard/emacs-dashboard/pull/493) for this feature.

**Comment by jcs090218** [comment]
@cvdub Thank you for the implementation! :)
