### ISSUE TITLE
dashboard-org-agenda-categories was removed?

### ISSUE THREAD

**Issue by saucoide** [emacs-dashboard/emacs-dashboard#320]
The documentation mentions `dashboard-org-agenda-categories` as a way to filter specific categories from the agenda

But it seems that part of the code was removed, it doesn't seem to be used anywhere

I can replicate the behavior with `dashboard-match-agenda-entry` doing something like this:

```elisp
(setq dashboard-match-agenda-entry "CATEGORY={Notes}")
```

But maybe the example from the documentation can be removed (or replaced with one using `MATCH`) if it's not relevant anymore

**Comment by jcs090218** [comment]
Thanks for the report! We have removed the misleading documentation from our README file. The variable `dashboard-org-agenda-categories` is also removed from the source code. Thanks! 🎉
