### ISSUE TITLE
Remove buffer file name from agenda section

### ISSUE THREAD

**Issue by mfxarc** [emacs-dashboard/emacs-dashboard#323]
I'd like to remove the buffer file name to not have these duplicate time
![DeepinScreenshot_select-area_20210823104403](https://user-images.githubusercontent.com/84589886/130457952-56b54065-32ad-4f43-b21a-d2a7b69eb1fc.png)
I found this in dashboard-widgets.el, but removing _file_ doesn't seem to do much
```
         (file (buffer-file-name)))
    (dashboard-agenda--set-agenda-headline-face item)
    (list item loc file)))
```

**Comment by ricardoricho** [comment]
Hi @mfxarc 
that file variable is used to jump to the agenda file when hitting enter. The string with the entry information is given by item
```elisp
(item (org-agenda-format-item
                (dashboard-agenda-entry-time (or schedule-time deadline-time))
                (org-get-heading)
                (org-outline-level)
                (org-get-category)
                (org-get-tags)
                t))
```
To remove the file name that you want, replace `(org-get-category)` with `""` 
```elisp
(item (org-agenda-format-item
                (dashboard-agenda-entry-time (or schedule-time deadline-time))
                (org-get-heading)
                (org-outline-level)
                ""
                (org-get-tags)
                t))
```

**Comment by ricardoricho** [comment]
@mfxarc Yes, like in many programming languages, you can always trim any string. You could replace the last line in the function `(list item loc file)` with `(list (string-trim item) loc file)`. You can use `string-trim` or just use `string-trim-left`

**Comment by mfxarc** [comment]
Worked just fine, thanks for the time.
