### ISSUE TITLE
How to get the line breaks in the dashboard?

### ISSUE THREAD

**Issue by apoorv569** [emacs-dashboard/emacs-dashboard#325]
I want the vertical lines after each category in the dashboard, but for some reason I am not able to show them. I have installed `page-break-lines` package, and turned it on globally, but nothing happens. Is there something else I need to enable to make this work?

**Comment by ricardoricho** [comment]
@apoorv569,  you have to set `dashboard-page-separator` to `"\n\f\n"`

**Comment by apoorv569** [comment]
> @apoorv569, you have to set `dashboard-page-separator` to `"\n\f\n"`

I added that, but still nothing shows up. Here is my full configuration,

```
  (use-package dashboard
    :straight t
    :init                                                                      ;; tweak dashboard config before loading it
    (setq dashboard-set-heading-icons t)                                       ;; add icons for headings
    (setq dashboard-set-file-icons t)                                          ;; add icons for files
    (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")     ;; set a title to be displayed under the banner
    (setq dashboard-startup-banner 'logo)                                      ;; use -official emacs -logo, or text banners -1,2,3
    (setq dashboard-center-content t)                                          ;; set to 't' for centered content
    (setq dashboard-items '((recents . 5)                                      ;; show some items on dashboard
                            (agenda . 5 )
                            (bookmarks . 5)
                            (projects . 5)
                            (registers . 5)))
    (setq dashboard-page-separator "\n\f\n")    ;; <-----
    :config
    (dashboard-setup-startup-hook)
    (dashboard-modify-heading-icons '((recents . "file-text")
                                      (bookmarks . "book")))
    :custom-face
      (dashboard-items-face ((t (:inherit widget-button :weight normal))))
      (dashboard-heading ((t (:inherit font-lock-keyword-face :weight semi-bold)))))
```

Also I have noticed even though the `agenda`, `bookmarks`, `projects`, `registers` and `recents` have value of 5, but only `recents` and `projects` show 5 items in the dashboard.

I don't have enough bookmarks and registers so I can't really say about those, but I do have 3-4 `agenda` currently but it only shows 2.

**Comment by ricardoricho** [comment]
Ok, one issue at a time. 
With `(setq dashboard-page-separator "\n\f\n")` you should see `^L` instead of the lines you want, right?
What happens if you try to enable `page-break-lines-mode` using `M-x`? 
How are you installing and enabling `page-break-lines`? 
I think it could be possible that the package is not available and maybe you have to add `:after page-break-lines` to `use-package`

**Comment by apoorv569** [comment]
> Ok, one issue at a time.
> With `(setq dashboard-page-separator "\n\f\n")` you should see `^L` instead of the lines you want, right?
> What happens if you try to enable `page-break-lines-mode` using `M-x`?
> How are you installing and enabling `page-break-lines`?
> I think it could be possible that the package is not available and maybe you have to add `:after page-break-lines` to `use-package`

Ok, I got it working. For some reason it was not able to detect that I changed the value to `\n\f\n` in the `dashboard-mode` but `helpful-variable` says the value changed. So I removed and reinstalled the `dashboard` package, now it shows the lines fine. No idea what the problem was.

**Comment by qkweint** [comment]
I am sure the author of this question meant **Horizontal** lines instead of "Vertical"
Unfortunately the fixes mentioned above did not work, and I am still experiencing this issue. If needed I will post my config file.

**Comment by jcs090218** [comment]
Can you try manually enable the mode, `M-x page-break-lines-mode`? I think this would just work. 😕

**Comment by qkweint** [comment]
Did not work.

**Comment by jcs090218** [comment]
I cannot reproduce this,

![Image 2](https://user-images.githubusercontent.com/8685505/165590104-4cb0c3c7-5d17-4df1-a457-62f9137e8122.png)

Did the character `^M` show up in the dashboard buffer?

**Comment by qkweint** [comment]
Could this be re-opened since I am still having this issue? this fix might have been a fluke or the author may have incorrectly deduced what fixed the issue.

**Comment by jcs090218** [comment]
This isn't a bug from `emacs-dashboard`, most likely to be the issue from user's configuration.

You could open another issue, and maybe we can discuss over there?

**Comment by qkweint** [comment]
https://github.com/emacs-dashboard/emacs-dashboard/issues/375
