### ISSUE TITLE
Agenda sort entries by scheduled date

### ISSUE THREAD

**Issue by ghost** [emacs-dashboard/emacs-dashboard#326]
The entries are being apparently sorted by the last modified file to the first, but I would like to sort them by their scheduled date. Is it a bug, or just misconfiguration?

**Comment by mlemosf** [comment]
I'm having the same problem, the entries are sorted on the agenda view but not on the dashboard.

**Comment by jcs090218** [comment]
You can now use variable `dashboard-agenda-sort-strategy` to sort.
