### ISSUE TITLE
Dashboard shows line numbers in terminal mode

### ISSUE THREAD

**Issue by wang1zhen** [emacs-dashboard/emacs-dashboard#329]
Hi, I'm using emacs in terminal mode, and every time I launch emacs in the terminal, the line numbers are shown as follows:
![image](https://user-images.githubusercontent.com/31798841/134796935-68251b4b-af0c-456c-b3fb-4ac8a7fe06cd.png)
and after any actions (i.e. creating a new window then delete it), the line numbers are not shown again. However, if a switch to another buffer then switches back, this issue persists.
This issue is not shown in GUI mode,
![image](https://user-images.githubusercontent.com/31798841/134797012-d68dc603-1399-49d0-a7b3-916288485157.png)
I'm showing the line numbers with =global-line-numbers-mode=, my configs are attached below.

```el
    (use-package display-line-numbers
      :ensure nil
      :hook (after-init . global-display-line-numbers-mode)
      :config
      (dolist (mode '(dashboard-mode-hook
                      org-mode-hook
                      term-mode-hook
                      eshell-mode-hook))
        (add-hook mode (lambda () (display-line-numbers-mode 0)))))

    (use-package dashboard
      :diminish
      :init
      (dashboard-setup-startup-hook)
      (when (< (length command-line-args) 2)
        (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))))
```

**Comment by jcs090218** [comment]
It does not seems like an issue from emacs-dashboard. You might have misconfigure `display-line-numbers-mode`? 😕

**Comment by wang1zhen** [comment]
Thank you, it seems if I enable the =global-display-line-numbers-mode= with `:init global-display-line-numbers-mode` instead of using an init hook, it works.
