### ISSUE TITLE
Add a face for `dashboard-footer-icon`

### ISSUE THREAD

**Issue by cyberknight777** [emacs-dashboard/emacs-dashboard#332]
By adding this, it would make customizing the footer-icon better.

**Comment by o0nd7ots** [comment]
+1

**Comment by jcs090218** [comment]
I somehow overlooked this feature. Anyways, feel free to open PRs for this feature! :)

**Comment by jcs090218** [comment]
The face `dashboard-footer-icon-face` is added. You can do:

```elisp
(setq dashboard-footer-icon (nerd-icons-faicon "nf-fa-heart" :face 'dashboard-footer-icon-face))
```

**Comment by o0nd7ots** [comment]
This is great. Thanks ricardricho!
