### ISSUE TITLE
Remove `(display-graphic-p)` checks from icon insertion

### ISSUE THREAD

**Issue by mohkale** [emacs-dashboard/emacs-dashboard#333]
I've got icons setup to properly render in my terminal but dashboard refuses to insert them because of these checks. I think it'd be better if you let users enable or disable it themselves by customizing the option instead of forcing a graphical frame check.

This is an issue with `dashboard-set-file-icons` and `dashboard-set-heading-icons`.

**Comment by jcs090218** [comment]
Are you running Emacs with emacsclient? Other than that, `display-graphic-p` should be sufficient.

**Comment by mohkale** [comment]
@jcs090218 

I'm running emacs in the **terminal** (also occasionally with emacsclient).

![my-emacs](https://media.githubusercontent.com/media/mohkale/emacs/master/.github/main.png)
