### ISSUE TITLE
Disable footer-icon

### ISSUE THREAD

**Issue by Evangeline-T** [emacs-dashboard/emacs-dashboard#338]
I wonder how to show footnote message without displaying footer-icon. 
I tried following configuration, and the entire footnote disappeared.
```lisp
(setq dashboard-footer-messages '("Happy Coding!"))
(setq dashboard-footer-icon nil)```

**Comment by jcs090218** [comment]
Try set `dashboard-footer-icon` to empty string.

```el
(setq dashboard-footer-icon "")
```

**Comment by Evangeline-T** [comment]
Thank you so much!!
