### ISSUE TITLE
I have problems with the last update and my agenda view

### ISSUE THREAD

**Issue by maxxcan** [emacs-dashboard/emacs-dashboard#345]
The message is: dashboard-filter-agenda-by-time: Symbol’s function definition is void: org-in-archived-heading-pError during redisplay: (dashboard-resize-on-hook #<frame emacs@argonauta 0x122ac30>) signaled (void-function org-in-archived-heading-p)

**Comment by maxxcan** [comment]
I respond to me. The problem is with Emacs 26.3. This problem disappears in the version 27.2

**Comment by jcs090218** [comment]
I reckon the error is from #340, yet the CI did pass in Emacs 26.3...
