### ISSUE TITLE
Add ace-link to dashboard

### ISSUE THREAD

**Issue by ddoherty03** [emacs-dashboard/emacs-dashboard#346]
This is a wish:  optionally allow links to be opened with ace-links so that the feel is consistent with other link-based modes, such as info, etc.

**Comment by ricardoricho** [comment]
Hi @ddoherty03 there is a new package https://github.com/emacs-dashboard/ace-link-dashboard

**Comment by jcs090218** [comment]
I have added ace-link support to [JCS-ELPA](https://github.com/jcs-emacs/jcs-elpa), just in case if anyone want to use it through `package.el`. It would be nice if we eventually publish it to MELPA.
