### ISSUE TITLE
No space between TODO and todo item

### ISSUE THREAD

**Issue by QMeqGR** [emacs-dashboard/emacs-dashboard#353]
In the agenda items list there are no spaces between the TODO and the todo item. It looks like

...   TODOthis has to be done
...   TODOnext item to be done

I'm using Emacs 29.0.50, everything else is from MELPA and is up-to-date.

**Comment by ricardoricho** [comment]
Hi, sorry for the mistake, the space is missing. A temporary fix, and maybe is something you still want to do, is to change `org-agenda-todo-keyword-format` from `"%-1s"` to `"%-5s"` or substitute  `5` with the max length of your keywords.

**Comment by QMeqGR** [comment]
Worked perfectly. Thank you!
