### ISSUE TITLE
what is shortcut-id??

### ISSUE THREAD

**Issue by gonsie** [emacs-dashboard/emacs-dashboard#356]
PR #348 / #349 added a new argument to `dashboard-insert-shortcut` called `shortcut-id`. What is this argument? I have been adding my own shortcuts for each section in my dashboard.

**Comment by jcs090218** [comment]
`shortcut-id` is the identifier you placed in `dashboard-item-shortcuts`. The changes are to make shortcut function name consistent to the identifier itself.

For instance, https://github.com/emacs-dashboard/dashboard-ls/commit/e74c0c554197359323a6738726ad2c366dcab509. You can leave it as `nil` if you don't want the shortcut to be recognized.
