### ISSUE TITLE
Open in other window

### ISSUE THREAD

**Issue by ppareit** [emacs-dashboard/emacs-dashboard#360]
Unable to open a link to a recent file or a bookmark in an other window.

An example for what I mean, assuming you have bookmarks:
Press `C-x r l` to open the bookmark list and now press `C-o` to open a bookmark in an other window.

This also does not work in `recentf-open-files` and the code of emacs-dashboard depends just like recentf on widgets. To me the problem that the call to `widget-button-press` is not flexible enough.

**Comment by jcs090218** [comment]
How about another approach? `ffap-other-window` should work similar to what you are asking.

**Comment by ppareit** [comment]
Kind of works. Still asks if this is the correct file. I can get around this using elisp. Does not work in Bookmarks. One also can get around this using elisp.

Still good workaround, can be used for my use case.
