### ISSUE TITLE
dashboard-banners-directory resolves with two slashes ("dashboard//banners") (GNU only?)

### ISSUE THREAD

**Issue by 93null** [emacs-dashboard/emacs-dashboard#367]
(Debian 10, EXWM, Emacs 27.1)
Relative banner paths don't work for me. Absolute paths do (text and image).
When evaluating the _dashboard-banners-directory_ function, I get two slashes "//" between my dashboard library directory and banner directory.
The _dashboard-banners-directory_ function uses the _file-name-directory_ function, and [the docs say](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Components.html):
```
On GNU and other POSIX-like systems, a string returned by this function always ends in a slash. On MS-DOS it can also end in a colon. 
```
So, I assume that's why it's evaluating to a path with an extra slash, and why relative banners don't work for me.
```lisp
(defconst dashboard-banners-directory
  (concat (file-name-directory (locate-library "dashboard")) "/banners/")
  "Default banner directory.")
```
I've only been using emacs for like a week and don't know enough to get this repo to build and see if changing "/banners/" to "banners/" would fix relative banner paths for my system.

**Comment by jcs090218** [comment]
This should resolved in ae5bf7b0cd88df10601e67104a401de5dab8eedd. Thanks for the bug report! :)
