### ISSUE TITLE
`M-x open-dashboard` makes dashboard buffer contents disappear

### ISSUE THREAD

**Issue by grendello** [emacs-dashboard/emacs-dashboard#384]
Hi,

I'm running emacs/master builds (currently on revision `a29e0f1c64f82f046d6ac89d194d3c019e933a33`) and
after a recent update of the package, the `*dashboard*` buffer shows up empty after switching to it
with `M-x open-dashboard` (it shows normal content after Emacs starts).  It appears that https://github.com/emacs-dashboard/emacs-dashboard/commit/35bcc2c3a45cd16c1ff66e19ead870c77172f2d0 is what 
caused the issue, since after I reverted the `dashboard.el` changes locally, everything went back to work as expected.

**Comment by jcs090218** [comment]
What's a `M-x open-dashboard`? Is this something from your config (or distro)? 😕 

I have added a CI test for activation and tested locally; I doubt the changes should cause any issue. 😅 

Let me know if this information helps!

**Comment by hatlafax** [comment]
Hi, I do have the very same problem. Calling my open-dashboard function yields into an emptied dashboard buffer. This is new behavior. My open function looks as

        (defun psimacs/dashboard/open-dashboard ()
          "Open the *dashboard* buffer and jump to the first widget."
          (interactive)
          ;; Check if need to recover layout
          (if (> (length (window-list-1))
                 ;; exclude `treemacs' window
                 (if (and (fboundp 'treemacs-current-visibility)
                          (eq (treemacs-current-visibility) 'visible))
                     2
                   1))
              (setq psimacs/config/dashboard-recover-layout-p t))

          (delete-other-windows)

          ;; Refresh dashboard buffer
          (when (get-buffer dashboard-buffer-name)
            (kill-buffer dashboard-buffer-name))

          (dashboard-insert-startupify-lists)
          (switch-to-buffer dashboard-buffer-name)

          ;; Jump to the first section
          (psimacs/dashboard/goto-recent-files))

I do not know, where I have copied that from. But I have changed it in accordance to
[ How to reopen the Dashboard #236 ](https://github.com/emacs-dashboard/emacs-dashboard/issues/236)
which works fine.

**Comment by jcs090218** [comment]
Awesome! I think @hatlafax has the correct workaround?

The previous implement does not make sense, and it's a legacy code (messy). Let me pin this issue due to the breaking changes.

**Comment by grendello** [comment]
Haha, I feel dumb :) I thought `open-dashboard` was a function defined somewhere in the `dashboard` code, while
I added it to my config over 2 years ago, copied from [this config](https://github.com/seagle0128/.emacs.d/blob/b353ce594245ef5de3d30ce3710797ca1869e42c/lisp/init-dashboard.el#L213-L231) (revision might be different). 
It was essentially the same one as in @hatlafax's case:

```elisp
  (defun open-dashboard ()
    "Open the *dashboard* buffer and jump to the first widget."
    (interactive)
    ;; Check if need to recover layout
    (if (> (length (window-list-1))
           ;; exclude `treemacs' window
           (if (and (fboundp 'treemacs-current-visibility)
                    (eq (treemacs-current-visibility) 'visible))
               2
             1))
        (setq dashboard-recover-layout-p t))

    (delete-other-windows)

    ;; Refresh dashboard buffer
    (when (get-buffer dashboard-buffer-name)
      (kill-buffer dashboard-buffer-name))
    (dashboard-insert-startupify-lists)
    (switch-to-buffer dashboard-buffer-name)

    ;; Jump to the first section
    (dashboard-goto-recent-files))
```

I updated it to the [latest version](https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-dashboard.el#L213-L232) from the same config and it works fine again:

```elisp
  (defun open-dashboard ()
    "Open the *dashboard* buffer and jump to the first widget."
    (interactive)
    ;; Check if need to recover layout
    (if (length> (window-list-1)
                 ;; exclude `treemacs' window
                 (if (and (fboundp 'treemacs-current-visibility)
                          (eq (treemacs-current-visibility) 'visible))
                     2
                   1))
        (setq dashboard-recover-layout-p t))

    ;; Display dashboard in maximized window
    (delete-other-windows)

    ;; Refresh dashboard buffer
    (dashboard-refresh-buffer)

    ;; Jump to the first section
    (dashboard-goto-recent-files))
```

**Comment by jcs090218** [comment]
I guess the question has been answered? Close this now! :D
