### ISSUE TITLE
The line is too short

### ISSUE THREAD

**Issue by linsui** [emacs-dashboard/emacs-dashboard#385]
![image](https://user-images.githubusercontent.com/36977733/177081507-5a5a104b-2549-4da1-a8c9-4ad61387124e.png)

Originally reported at https://github.com/seagle0128/.emacs.d/issues/366. Thanks!

**Comment by jcs090218** [comment]
It seems like an issue from `page-break-lines`, have you configured the package? 😕

**Comment by linsui** [comment]
No, it's the https://github.com/seagle0128/.emacs.d out of the box.

**Comment by jcs090218** [comment]
Does this only affect the dashboard buffer? Would `page-break-lines` work in other buffer?

**Comment by linsui** [comment]
How should I test?

**Comment by jcs090218** [comment]
You will need to understand `page-break-lines`, it simply replace `^L`  to `─` times the window width. So to test it with other buffer, simply insert `^L` (`\f`) and hit `M-x page-break-lines-mode`. Following code should help,

```elisp

(defun my-test ()
  (interactive)
  (insert "\f")
  (page-break-lines-mode 1))
```

`eval` it and `M-x my-test`.

**Comment by linsui** [comment]
![image](https://user-images.githubusercontent.com/36977733/177982392-58745bbd-751f-4716-a1b3-ce4af67366de.png)

I got this.

**Comment by jcs090218** [comment]
It seems like it does not work in other buffer as well. I guess the bug is from the upstream. 😅 

Try report it to https://github.com/purcell/page-break-lines.

**Comment by linsui** [comment]
Thanks! Looks like it has been reported [here](https://github.com/purcell/page-break-lines/issues/36).

**Comment by seagle0128** [comment]
I found the workaround to address this issue. I committed a patch, but I'm not sure if it has other side-effects.
Please test the latest.
