### ISSUE TITLE
Center content before GUI loads

### ISSUE THREAD

**Issue by Visne** [emacs-dashboard/emacs-dashboard#386]
Currently, the dashboard is first shown left-aligned and then a short moment later the content snaps to the center, if configured. While not a functional problem, this is pretty jarring.

I was wondering whether this is expected behaviour in the first place (maybe there's something wrong with my config), and if so whether this is fixable.

I've tried moving different config settings to early-init.el, but I didn't manage to fix it.

**Comment by jcs090218** [comment]
It seems like you are trying to render dashboard before it should be rendered. Make sure you have configured dashboard before you actually called the rendering function. Try debug your configuration or test it with `emacs -q` environment. If the issues persist, then it could be the bug in this package.

Hope the information helps!
