### ISSUE TITLE
Better approach for emacsclient

### ISSUE THREAD

**Issue by mmahmoudian** [emacs-dashboard/emacs-dashboard#388]
The following information from the README is suboptimal:

> In addition to the above, configure `initial-buffer-choice` to show Dashboard in frames created with `emacsclient -c` as follows:
> 
> ```elisp
> (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
> ```

This is suboptimal because the first time after `emacs --bg-daemon` that a frame is created, it will not properly load the dashboard with all the graphics:

![image](https://user-images.githubusercontent.com/390889/177763775-5e36f1b4-926b-4db7-bcff-3e926fda901d.png)

and the user have to reload the config to get it fixed. This is most probably because the `initial-buffer-choice` is run before any frame exists, and therefore everything is in text-only mode.

A better way would be to have

```elisp
(add-hook 'server-after-make-frame-hook (lambda()
    (switch-to-buffer dashboard-buffer-name)
    (dashboard-mode)
    (dashboard-insert-startupify-lists)
    (dashboard-refresh-buffer)))
```

which uses [a proper hook](https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Frames.html#index-server_002dafter_002dmake_002dframe_002dhook) and also does not disturb the `emacsclient --tty --create-frame`. The content of the lambda is inspired from https://github.com/emacs-dashboard/emacs-dashboard/issues/236#issuecomment-711360926 

I suggest removing this section from README (or move it to some other section) and instead extend the `dashboard-setup-startup-hook` function to contain the hook above as well.

If you agree with this suggestion, I can create a PR.

**Comment by jcs090218** [comment]
After some investigation, I would suggest people use `server-mode` instead of the `--daemon` option. WDYT?

**Comment by mmahmoudian** [comment]
Thanks for your reply. I'm n00b in Emacs world, but according to [the official Emacs manual ](https://www.gnu.org/software/emacs/manual/html_node/emacs/Emacs-Server.html):

> Run the command `server-start` in an existing Emacs process: either type `M-x server-start`, or put the expression `(server-start)` in your init file (see [The Emacs Initialization File](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html)). **The existing Emacs process is the server; when you exit Emacs, the server dies with the Emacs process.**

The issue is the last part that I made bold.

Also it seems the preferred method in Emacs is `--daemon`. They have extensive documentation about it, plus the systemd part also points to that direction. The way I use Emacs is to run `emacs --bg-daemon` upon startup and I frequently open and close frames when I need them, plus I can jump to buffers that are in other frames from the buffer list of the current active frame which is super handy.

Regarding this feature-request of mine, I believe it does not change the behavior of this package for users, but it will solve the problem for those who are daemon users. Considering that you already have a function to add hooks, I though this can be a great addition.

I think at the end it boils down to your preference as you are the owner of this repo and this awesome package.

**Comment by mmahmoudian** [comment]
Do you want to file an issue with the upstream (emacs itself)? Although unfortunately emacs development is super slow (according to their version releases), and would take them a year or so to address this

**Comment by jcs090218** [comment]
I may not have time to keep up the Emacs development, so it would be great if someone else volunteer to do so. But if no one willing to do, then I will file an issue/feat. request to the upstream.

**Comment by mmahmoudian** [comment]
@jcs090218 tbh I don't think I'm knowledgeable enough to either ask for the correct thing upstream, or to know what amount of change is desired to make this snappy and fast.

In your opinion does it make sense to ask on IRC?

**Comment by jcs090218** [comment]
Sorry for another delay on this issue. Was being busy with something else! 😓 

> tbh I don't think I'm knowledgeable enough to either ask for the correct thing upstream, or to know what amount of change is desired to make this snappy and fast.

I don't know if it's possible since running `--daemon` has to be in TUI environment, and my guess is that's why they implemented `server-mode` for the GUI environment. Just make sure we lead them to the right direction. 😅 

> In your opinion does it make sense to ask on IRC?

It would make sense on IRC, or file a feature request should be sufficient.
