### ISSUE TITLE
backspace is not worked

### ISSUE THREAD

**Issue by dian-yu-luo** [emacs-dashboard/emacs-dashboard#389]
when cursor stay on the project item, type <backspace> can't delete current project item

**Comment by jcs090218** [comment]
Are you using `projectile`?

Is still in `TODO`...

https://github.com/emacs-dashboard/emacs-dashboard/blob/f4e8ed9f0dd2147d4f076948ff7f6c7333042c91/dashboard.el#L315

**Comment by dian-yu-luo** [comment]
I am not sure which one I use. I use default .
so need I use other package? or something else

**Comment by jcs090218** [comment]
Check your variable `dashboard-projects-backend`, it's default to `projectile`. If you want to use default:

```elisp
(setq dashboard-projects-backend 'project-el)
```

**Comment by dian-yu-luo** [comment]
that worked

**Comment by jcs090218** [comment]
Looks good, would you like to send a PR for this?

**Comment by jcs090218** [comment]
Closing this now since #390 get merged.
