### ISSUE TITLE
Sort agenda by priority

### ISSUE THREAD

**Issue by jhp0tter** [emacs-dashboard/emacs-dashboard#400]
It seems like there are only options to sort the agenda by time and status, but not by priority:

https://github.com/emacs-dashboard/emacs-dashboard/blob/02c350d7a767f577c8cccee84904c423f86fae54/dashboard-widgets.el#L1072-L1076

The `org-agenda` view sorts by priority by default so I was expecting that I would be able to do the same in the Dashboard, but it seems not?

**Comment by jcs090218** [comment]
@ricardoricho Any thoughts?

**Comment by ricardoricho** [comment]
Sure, it won't be a problem to add `priority-up` and `priority-down` strategies.

**Comment by jhp0tter** [comment]
#401
