### ISSUE TITLE
Defer loading projectile?

### ISSUE THREAD

**Issue by goldfita** [emacs-dashboard/emacs-dashboard#406]
I spent about 20 minutes trying to figure out why projectile was loading at startup. I finally traced it to the following line:

`(projects  . 5)`

I was wondering if there is any way to defer loading and still have dashboard list my projects? I'm not sure how it's getting the list of projects. If it needs to load projectile to get the list, then obviously this would not be possible. But maybe it reads a file or uses some standard emacs mechanism.

**Comment by ricardoricho** [comment]
Hi @goldfita, we are [loading projectile](https://github.com/emacs-dashboard/emacs-dashboard/blob/554dc6fac1362dd6b66318c8250eea8bd63aa92f/dashboard-widgets.el#L1034), to use `projectile-cleanup-known-projects` and then `projectile-load-known-projects` which returns the list of projects.

**Comment by goldfita** [comment]
OK. It might be helpful to make it clear in the readme that setting dashboard-items is also loading things.

**Comment by goldfita** [comment]
I also noticed bookmarks is forcing tramp to load since I have remote bookmarks.

**Comment by goldfita** [comment]
I've removed projects and bookmarks from dashboard for now. I might add them in if my init file ever reaches a point of stability. But due to frequent opening and closing Emacs, it's not worth the extra second load time for features I don't use often.

I have been thinking about a possible solution to this. Would it be possible to add optional expansion regions and only load packages when a region is expanded? For example, if I had the following configuration

```elisp
(setq dashboard-items 
  '((recents . (20 t))
    (projects . 5)
    (bookmarks . 10)))
```

then dashboard would initially look like this

> \- Recent Files
> ......Text File A.txt
> ......Text File B.txt
> \+ Projects
> \+ Bookmarks

At most there is only ever a need to select from one item, so there is no need to pull in everything.

**Comment by jcs090218** [comment]
We are not pull in everything unless the user require to do so. Follow this logic, if you have `(projects . 5)`, then project must be called and pulled in. The only way to get around this, is to have some kind of exposed function (minimal version) of that specific module. So it won't pull in everything, but it's often not worth to do it this way.

**Comment by jcs090218** [comment]
Since there is nothing we can do at the moment, closing this issue.
