### ISSUE TITLE
Cannot use image as banner

### ISSUE THREAD

**Issue by channel-42** [emacs-dashboard/emacs-dashboard#410]
My emacs version: `GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6) of 2022-09-12`

Dashboard version: `20221116.1155`

When `dashboard-startup-banner` is set to an image, dashboard fails to start and shows: 

`dashboard-choose-banner: Symbol’s function definition is void: image-supported-file-p`. 

Text banners still work.

**Comment by jcs090218** [comment]
This is due to #407, proposed fix is #409. Can you test if the patch works?

**Comment by channel-42** [comment]
Thanks for the quick reply! 
#409 fixes the issue on my end 👍🏼

**Comment by jcs090218** [comment]
Thanks for the confriming this! ;)
