### ISSUE TITLE
"dashboard-text-banner" customization not working?

### ISSUE THREAD

**Issue by SATYADAHAL** [emacs-dashboard/emacs-dashboard#411]
I am trying to customize the ASCII banner with following code:
```
(set-face-attribute 'dashboard-text-banner nil
    :foreground "#FF0BAF"
    :weight 'bold
    :slant 'italic
    :height 80
    )
```
As mentioned the  [readme](https://github.com/emacs-dashboard/emacs-dashboard/#faces"). I was able to customize different faces except for the ASCII text banner.
1. dashboard-banner-logo-title
2. dashboard-text-banner
3. dashboard-heading
4. dashboard-items-face

I am using GNU Emacs 28.1. 
I installed this package using MELPA. I also manually installed by cloning this repo but it also didnot work.
Is this bug in the program or Am I doing something wrong.

**Comment by jcs090218** [comment]
I think it got removed in #407. 

cc @Stebalien 😖

**Comment by SATYADAHAL** [comment]
Could you remove it from README also?

**Comment by jcs090218** [comment]
> Could you remove it from README also?

We should retrieve this behaviour  so there is no need to remove it from README.

**Comment by SATYADAHAL** [comment]
Hope to see the update soon. I will using the older version till then. I will this issue when this feature is retrieved.
