### ISSUE TITLE
dashboard-insert-banner: Symbol’s value as variable is void: file-exists-p

### ISSUE THREAD

**Issue by khinshankhan** [emacs-dashboard/emacs-dashboard#414]
When using a custom banner, I get the error `dashboard-insert-banner: Symbol’s value as variable is void: file-exists-p`. This is the setting logic:
```lisp
  (setq dashboard-startup-banner (if shan--settings-exist?
                                     shan--preferred-logo
                                   'logo))
```
I've confirmed `dashboard-startup-banner` points at the right file absolute path using `M-:` and printing its value. I've also confirmed this isn't an issue with the startup hook by killing the buffer and using `dashboard-insert-startupify-lists`, which results in the same error. 

Using 
```lisp
  (setq dashboard-startup-banner 'logo)
```
works fine for the logo, which I'm using for now.

**Comment by jcs090218** [comment]
Hmm... I am not able to reproduce this. Can you tell me what is the value of `shan--preferred-logo`? A string? File path? etc.

cc @Stebalien Any thoughts? 😅

**Comment by Stebalien** [comment]
Looks like the `not` pattern was added to pcase in emacs 28. I'll submit a quick patch to not use that (pun intended).

**Comment by Stebalien** [comment]
(I did not expect this much fallout from that patch, I'm sorry about that)

**Comment by jcs090218** [comment]
> (I did not expect this much fallout from that patch, I'm sorry about that)

No no, you make quick responses and keep sending patches on these later issues. You did great!, and I appreciate it! ;)

**Comment by khinshankhan** [comment]
The value was the string `/Users/khinshankhan/.emacs.d/personal/work-banner.png"`.

The patch works dandy, my work mac is indeed on 27.2, so that was the issue. 

Thank you!
