### ISSUE TITLE
Dashboard interrupts startup when using Emacs without X support

### ISSUE THREAD

**Issue by 6b6279** [emacs-dashboard/emacs-dashboard#417]
I am using the Arch Linux `emacs-nox` package and since the last update dashboard fails to load after inserting the Emacs logo in the dashboard buffer. The logo itself seems to be rendered correctly (see attached picture) but immediately after that Emacs emits `Invalid image type 'png'` and stops evaluating the initfile. When running in daemon mode, Emacs can’t get beyond `(dashboard-setup-startup-hook)` and hangs up indefinitely during evaluation. Disabling the logo completely using `(setq dashboard-startup-banner nil)` seems to do fix the issue, though.
![20221204_21h26m44s_grim](https://user-images.githubusercontent.com/109346960/205513839-9cc1eaba-02cf-452d-b8e7-5148951e826b.png)

**Comment by jcs090218** [comment]
Hi, what version of Emacs are you using? What's the value in variable `dashboard-startup-banner`?

I don't think this is an issue from this package, would it be an upstream Emacs issue? 😕 

cc @Stebalien WDYT?

**Comment by Stebalien** [comment]
Nah, this was my mistake. I assumed that PNGs were supported, but emacs-nox isn't built with PNG support. #418 checks this.
