### ISSUE TITLE
Dashboard no longer shows up on emacs startup

### ISSUE THREAD

**Issue by JosephFerano** [emacs-dashboard/emacs-dashboard#421]
I recently upgraded to the latest Dashboard and found that it wasn't loading on startup. I have tried numerous things but the only thing I have found to work is by reverting the package to commit 554dc6f. Commit 48860b1 seems to be the one that introduced the issue for me. I cloned the package with straight so by reverting the commit, then deleting the cached build, it fixes itself.

There are no errors showing up. Here is what I currently have in my config

```lisp
(straight-use-package 'dashboard)
(require 'dashboard)
(dashboard-setup-startup-hook)
(setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
(setq dashboard-items '((recents  . 8)
                        (bookmarks . 8)))
(setq dashboard-startup-banner 'logo)
(setq dashboard-center-content t)
(setq dashboard-set-file-icons t)
(setq dashboard-set-navigator t)
(setq dashboard-set-heading-icons t)
(add-hook 'dashboard-mode-hook (lambda () (setq-local line-spacing 12)))
```
I have tried just this
```lisp
(straight-use-package 'dashboard)
(require 'dashboard)
(dashboard-setup-startup-hook)
```

And it still doesn't work.

Thank you for your help. Great package!

**Comment by JosephFerano** [comment]
So it seems to be related to chemacs2. I moved my vanilla config to .emacs.d/ and now it works again. So something happened after that commit where loading with chemacs2 doesn't work anymore.

**Comment by jcs090218** [comment]
Since there is nothing we can do on our side, I think this issue can be close now? Thanks!
