### ISSUE TITLE
Changing face height of title breaks centering

### ISSUE THREAD

**Issue by Manueljlin** [emacs-dashboard/emacs-dashboard#426]
Changing the height of `dashboard-banner-logo-title` (either by yourself or by a theme like [catppuccin](https://github.com/catppuccin/emacs/blob/86b16248ef2ce450def4a00a0ca5170c102da623/catppuccin-mocha-theme.el#L516)) results in the text being offset to the right.

Seems reproducible with any font family. In this case, I've disabled all of my custom faces to show it's just the height affecting this.

![image](https://user-images.githubusercontent.com/11275573/210182106-037338f9-04dd-4a5b-83d5-2e4d570f4dbd.png)
![image](https://user-images.githubusercontent.com/11275573/210182112-fae2f97a-4fee-4266-bd55-8af588590a43.png)
![image](https://user-images.githubusercontent.com/11275573/210182122-42bc3acd-4988-4494-beb3-d743376f15bb.png)
line-prefix and index-prefix show the same snippet.

`GNU Emacs 28.2 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)`

**Comment by jcs090218** [comment]
Fixed in #427. Thanks!
