### ISSUE TITLE
Last character in `dashboard-init-info` gets cut out

### ISSUE THREAD

**Issue by Manueljlin** [emacs-dashboard/emacs-dashboard#428]
![image](https://user-images.githubusercontent.com/11275573/210287240-4771b06e-54b3-439d-9d6d-a651e56a8c10.png)
sorry for the spam :sweat_smile:

**Comment by jcs090218** [comment]
Thanks for reporting this issue. Didn't realize that until now! 😅 

Fixed in #429.

**Comment by Manueljlin** [comment]
thanks again :D
