### ISSUE TITLE
Dashboard not appearing at startup after updating package

### ISSUE THREAD

**Issue by IlIllII** [emacs-dashboard/emacs-dashboard#433]
Hello!

I've updated to the most recent version of `emacs-dashboard` and now the dashboard no longer appears when I start emacs. Prior to updating the package, my emacs would start and display the dashboard. I use emacs 28.1 if that matters.

When emacs starts, a dashboard buffer appears but it is an empty buffer. Calling `M-x dashboard-refresh-buffer` displays the dashboard as normal.

I saw https://github.com/emacs-dashboard/emacs-dashboard/issues/421. The issue seems the same, however I do not use chemacs.

**Comment by IlIllII** [comment]
I haven't found the cause of the issue, but I've found a work-around by calling `(dashboard-refresh-buffer)` at the end of my init file.

**Comment by jhncondix** [comment]
I use emacs 27, but had a similar issue when I upgraded to the latest dashboard version on melpa. Using emacs client the icons stopped appearing. In my case, however, the rest of the dashboard with the file lists appeared. Just no icons except the main emacs icon.  I just tried your suggestion of `M-x dashboard-refresh-buffer` and sure enough that causes the icons to appear. But adding it to my init.el didn't work. I did not have this problem when running emacs client before the recent upgrade.

**Comment by rynoV** [comment]
Also running into this after installing for the first time and following the readme. Only running into it in new frames with the daemon, starting up initially shows the dashboard as expected. Switching to this fixes it (perhaps the readme should be updated?):

```elisp
(setq initial-buffer-choice (lambda ()
                                (get-buffer-create "*dashboard*")
                                (dashboard-refresh-buffer)))
```

**Comment by jcs090218** [comment]
We are trying to maintain the previous behavior, but apparently, there is a bug after a few significant changes. As of right now, the bug is quite confusing and hard to track down. 😓 Sharing ideas and presenting workarounds in the community is great; we, the maintainers are collecting information and hope we can eventually resolve this bug.

And sorry for the inconvenience! 😓

**Comment by 6b6279** [comment]
I can’t reproduce this issue. `(dashboard-startup-hook)` adds `(switch-to-buffer dashboard-buffer-name)` to `emacs-startup-hook`, so modifying `initial-buffer-choice` shouldn’t be necessary, no? I am on Emacs 28.2, using the upstream version of `emacs-dashboard`.

**Comment by swi2012** [comment]
> I use emacs 27, but had a similar issue when I upgraded to the latest dashboard version on melpa. Except for me the issue only occurred using emacs client. When running it as a client the icons stopped appearing. In my case, however, the rest of the dashboard with the file lists appeared. Just no icons except the main emacs icon. I just tried your suggestion of `M-x dashboard-refresh-buffer` and sure enough that causes the icons to appear. Thanks! But adding it to my init.el didn't work. I did not have this problem when running emacs client before the recent upgrade.
> 
> Update: I added this to init.el, which fixed the problem:
> 
> `(add-hook 'server-after-make-frame-hook 'dashboard-refresh-buffer)`

Thanks for idea, but on my end it break magit commit somehow. I've changed it a little like this, now dashboard fixed and magit commit works:
```elisp
 (add-hook 'server-after-make-frame-hook
            (lambda ()
              (when (eq (buffer-local-value 'major-mode (current-buffer)) 'dashboard-mode)
                (dashboard-refresh-buffer))))
```

**Comment by JosephFerano** [comment]
Just to comment that I am still experiencing the same behavior I ran into and reported on #421, the only thing that fixes it for me is reverting back to that commit. I am on emacs 29

**Comment by jhncondix** [comment]
Once again, for me an upgrade broke some dashboard functions. I am on Emacs 28.1and had dashboard-20230331.2304. When I upgraded to 20230503.1851 the icons from all-the-icons no longer appeared. I managed to get all of them back except the dot icons for org agenda. The section in customize for setting the value "dashboard-agenda-item-icon" had the buttons for setting and saving the proper value greyed out. It seems like the upgrade is incompatible with emacs 28.1 in some strange way.

**Comment by jcs090218** [comment]
@jhncondix What is your icon type? Try modify the variable `dashboard-icon-type`.

**Comment by jhncondix** [comment]
I had that set to all-the-icons.

**Comment by jcs090218** [comment]
No backtrace at all? 🤔

**Comment by amartos** [comment]
Hi.

I also had this issue recently, and just made a pull request.

The config I use, for reference:


```elisp
  (setq user-dashboard-dev "/home/alexandre/archives/projects/emacs-dashboard/")
  (add-to-list 'load-path user-dashboard-dev)
  (byte-recompile-directory user-dashboard-dev 0)

  (use-package dashboard
    :after (project org all-the-icons)
    :custom
    (dashboard-startup-banner user-avatar)
    (dashboard-projects-backend 'project-el)
    (dashboard-projects-show-base 'align)
    (dashboard-items '((projects . 3) (bookmarks . 3) (recents . 3) (agenda . 10)))
    (dashboard-navigator-buttons
      (list
        (mapcar
          #'(lambda (elmt)
              (append
                (list (substring-no-properties (all-the-icons-faicon (car elmt) :height 20)))
                (butlast (cdr elmt))
                (list #'(lambda (&rest _) (browse-url (last elmt))))
                ))
          user-websites
          )
        )
      )
    (dashboard-set-heading-icons t)
    (dashboard-set-file-icons t)
    (dashboard-set-navigator t)
    (dashboard-week-agenda nil)
    :custom-face
    (dashboard-items-face ((nil (:weight normal))))
    :config
    (dashboard-setup-startup-hook)
    ;; This hack was needed without the fix, but still unstable at least.
    ;; (add-hook 'after-make-frame-functions #'(lambda (&rest _) (dashboard-open) (dashboard-refresh)))
    ;;:pin melpa
    :pin manual
    :ensure nil)
````
