### ISSUE TITLE
Org agenda entry height 

### ISSUE THREAD

**Issue by w0lper** [emacs-dashboard/emacs-dashboard#434]
**Problem**:
My dashboard agenda displays entries with a greater height than the other items (screenshot below). Using `C-u C-x =`, I found out they are getting this "extra" height from the face attribute org-level-1, 2, 3... (from outline-X inherit more specifically). 

Everything I've tried to fix it either failed or broke my org-mode (like disabling the inherit outline from org-level). I also tried messing a bit with the `dashboard-agenda-entry-format`, but after a afternoon of failures, I can say it was beyond my newcomer knowledge. 

Anyway, I would appreciate any help or enlightenment to solve this in a smart way.

**Dashboard version**: 20230108.1149
**Emacs version**: 27.1
**Screenshot**:
![Screenshot from 2023-01-23 15-49-49](https://user-images.githubusercontent.com/120055499/214124321-3bd6b690-9cd1-4ec0-b36b-bd1098021de5.png)
**Dashboard related config**:
```
  (setq inhibit-startup-message t)

  (setq initial-buffer-choice (lambda () (dashboard-refresh-buffer)(get-buffer "*dashboard*")))

  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-startup-banner "~/.emacs.d/img/dashLogo.png")
    (setq dashboard-items '((recents  . 5)
                            (projects . 5)
                            (bookmarks . 5)
                            (agenda . 5)))    
    (setq dashboard-center-content t)
    (setq dashboard-set-file-icons t)
    (setq dashboard-banner-logo-title "Welcome back, Wolper!")
    (setq dashboard-agenda-sort-strategy '(time-up))
    (setq dashboard-agenda-prefix-format "%i %-12:c %s "))

  (add-hook 'dashboard-mode-hook 'variable-pitch-mode) ; related to below which comes earlier in my config

(custom-theme-set-faces
     'user
     '(variable-pitch ((t (:family "Iosevka Aile"))))
     '(fixed-pitch ((t ( :family "Iosevka  Medium"))))
     '(org-block ((t (:inherit fixed-pitch))))
     '(org-code ((t (:inherit (shadow fixed-pitch)))))
     '(org-table ((t (:inherit fixed-pitch))))
     '(org-indent ((t (:inherit (org-hide fixed-pitch))))))
```

**Comment by ricardoricho** [comment]
Hi @w0lper, nice wallpaper and Emacs logo. What theme are you using? 
Usually themes modify the org faces, we are getting the face depending on the org-outline-level of the entry.

Currently, there is no way to modify the dashboard-agenda faces without modifying some faces (if not all)  in `org-level-faces`. It would be nice to "normalized" the height of the faces without declaring another particular face.

**Comment by w0lper** [comment]
Hey @ricardoricho , thanks! Logo is from Uncle Dave's build. That was pretty accurate. I'm using `zerodark` theme which changes my org level faces as follows:

```
   (custom-theme-set-faces
   'zerodark
    ...
   `(outline-1 ((,class (:foreground ,peach :weight bold :height 1.3))))
   `(outline-2 ((,class (:foreground ,purple :weight bold :height 1.2))))
   `(outline-3 ((,class (:foreground ,blue :weight bold :height 1.1))))
   `(outline-4 ((,class (:foreground ,green-light :weight bold))))
   `(outline-5 ((,class (:foreground ,peach :weight bold))))
   `(outline-6 ((,class (:foreground ,purple :weight bold))))
   `(outline-7 ((,class (:foreground ,blue :weight bold))))
   `(outline-8 ((,class (:foreground ,green-light :weight bold))))
```
Tested changing these `height` values to `1.0` and it did the trick perfectly in the dashboard agenda! :+1: 

The thing is, I would like to keep these different height values in org-mode due to readability reasons, mainly because I will use Emacs more for prose than coding. Do you think I can overwrite these theme values only in dashboard buffer/mode? Or would be better/easier to erase height variables from the theme source code and try to change org-levels height through my config? 

(I'm searching on it right now and testing some stuff)

**Comment by w0lper** [comment]
Thank you very much, @ricardoricho! Working perfectly.

![Screenshot from 2023-01-27 00-38-57](https://user-images.githubusercontent.com/120055499/215004849-17077639-4932-47ab-bea8-e3064eed55de.png)

Long live free software freedom :smiling_face_with_tear:
