### ISSUE TITLE
Feature request: create a function that creates the dashboard and switches to it

### ISSUE THREAD

**Issue by dmgerman** [emacs-dashboard/emacs-dashboard#437]
Correct me if I am wrong. If the buffer *dashboard* is killed, there is no current method to display it again.

Ideally, create a function that, when called, creates the buffer and switches to it.

**Comment by ricardoricho** [comment]
Hi @dmgerman the function is called `dashboard-refresh-buffer`.

**Comment by dmgerman** [comment]
Thank you. It seems that it does what I wanted. May I suggest adding it to the readme?

**Comment by andyjda** [comment]
Hi @dmgerman some more context on this: the initial conversation happened on [this Reddit post](https://www.reddit.com/r/emacs/comments/11382ux/comment/j8opd33/), where we mentioned that it'd be nice to have the option to delay opening the dashboard. 

In other words, the user would have the option to set the dashboard to not open by default upon startup, but to still be able to open the dashboard at a later time if needed. Thanks for pointing out that `dashboard-refresh-buffer` accomplishes this. I think for the feature to be complete it's just missing the fact that this command should be autoloaded. See [my PR ](https://github.com/emacs-dashboard/emacs-dashboard/pull/439) for an example implementation.


Also, out of curiosity, what is the purpose of `redisplay` in the `dashboard-setup-startup-hook`? Could this be rewritten as simply:

```
(defun my-dashboard-setup-startup-hook ()
  "Setup post initialization hooks.
If a command line argument is provided, assume a filename and skip displaying
Dashboard."
  (when (< (length command-line-args) 2)
    (add-hook 'after-init-hook (dashboard-open))))
```
