### ISSUE TITLE
Icons on Custom Widgets

### ISSUE THREAD

**Issue by ayman** [emacs-dashboard/emacs-dashboard#444]
Is there a way to add an icon to a custom widget? 

`(defun dashboard-insert-heading (heading &optional shortcut)` in `dashboard-widgets.el` has a `cond` which catches the built in section types but I couldn't see how to have that match a custom section with icon.

I have an easy modification to `dashboard-insert-heading` to make this work but wanted to check here first before submitting the pull request.

**Comment by ricardoricho** [comment]
Hi @ayman you're right! That `cond` inside [`dashboard-insert-heading`](https://github.com/emacs-dashboard/emacs-dashboard/blob/b648a45684677aa29cdb00e4d14d02dd9fa9cb68/dashboard-widgets.el#L483) makes the icons insertions closed to other widgets.
Please submit your pull request.
