### ISSUE TITLE
Shortcuts for cutom items

### ISSUE THREAD

**Issue by pprevos** [emacs-dashboard/emacs-dashboard#448]
Hi, I created a custom item like below. How can I activate the keyboard shortcut?

P.S. I am working on auxiliary functions for the Denote note-taking package.

```
  (defun dashboard-insert-denote-stats (list-size)
    "Helper function to display Denote summary on the Emacs Dashboard.
  LIST-SIZE is a dummy variable required by the dashboard package."
    (dashboard-insert-heading "Denote:"
                              "d"
                              (all-the-icons-octicon
                               "file-text"
                               :height 1.2
                               :v-adjust 0.0
                               :face 'dashboard-heading))
    (insert "\n")
    (insert (concat "    ⚫  " (denote-explore-count-notes) "\n"))
    (insert (concat "    ⚫  " (denote-explore-count-keywords))))

  (add-to-list 'dashboard-item-generators
               '(denote . dashboard-insert-denote-stats))

  (add-to-list 'dashboard-items '(denote) t)
```

**Comment by ricardoricho** [comment]
Hi @pprevos, try using `(dashboard-insert-shortcut 'denote "d" "Denote:")` after `dashboard-insert-heading`

I think that should work because you don't have a list of items. 
Are you working on some "dashboard-denote" package?

**Comment by pprevos** [comment]
Hi, thanks for the response. That worked a treat.

I am working on the [denote-explore package](https://github.com/pprevos/denote-explore) with some auxiliary functions for Denote. Do you use it?
