### ISSUE TITLE
Other icons than `all-the-icons`?

### ISSUE THREAD

**Issue by StrictlyMonad** [emacs-dashboard/emacs-dashboard#449]
**Description:**
I recently came across [nerd-icons.el](https://github.com/rainstormstudio/nerd-icons.el) and was in the process of migrating to it from `all-the-icons` until I stumbled upon an error when I hopped into emacs-dashboard.

**Experienced error**: 
The cause for the error menitoned below is due to the hardcoded all-the-icons support that emacs-dashboard has.

```
Package `all-the-icons` isn't installed.
```

Therefore I'd like to ask, is there any room for a general approach which allows us to use either `all-the-icons` or `nerd-icons`?

**Comment by jcs090218** [comment]
Sounds good to me. However, I don't have much time for this, so we are open for PR(s). 😅

**Comment by StrictlyMonad** [comment]
Good that we at least got the go! But now the issue is, someone else than me have to help out since I am still a beginner when it comes to writing lisp code.. :/

**Comment by lebensterben** [comment]
I'll make a PR.

**Comment by lebensterben** [comment]
The following icon is missing from nerd-icons:

[] \uf464 nf-oct-history

**Comment by lebensterben** [comment]
After some tinkering I found that it's not practical to use `nerd-icons` because *they are too small*.

For example, you can try to evaluate the following:

```elisp
(insert (all-the-icons-octicon "history" :height 1.2 :v-adjust 0.0)
        (nerd-icons-octicon "nf-oct-history" :height 2.4 :v-adjust -0.135)
        "Lorem Ipsum")
```

The icons look roughly the same size, but due to `:height 2.4` on `nerd-icons`, the line is way too tall!

If I adjust the height smaller, then the icon becomes illegible.

**Comment by jcs090218** [comment]
Hmmm.. can you post a screenshot? Isn't nerd icons just regular "text"(s)? 🤔

**Comment by lebensterben** [comment]
![2023-04-23_02-22](https://user-images.githubusercontent.com/1222865/233823417-3e38c4f5-e22e-48a5-917e-871b480fc9c1.png)

This is the end result.
You can see that after adjust `:height` and `:v-adjust` properties, I managed to make the icon and text roughly the same size and aligned well, but the line height is artificially enlarged by too much!

**Comment by jcs090218** [comment]
Ah, okay. For me, the icons don't have to be larger, so a regular size icon will fit my usage.

**Comment by lebensterben** [comment]
@jcs090218 they are way to small by default.

Just go to ielm and 

```elisp
(insert (all-the-icons-octicon "history")
        (nerd-icons-octicon "nf-oct-history")
        "Lorem Ipsum")
```

and you will get what I'm saying.

Too make the icon barely readable, the `:height` value needs to be at least 1.6 probably but that's already too large.

**Comment by StrictlyMonad** [comment]
I spoke to the author recently and they are considering adding a font-size option to the package. Perhaps that could help resolve the "small icons" issue that you are facing.

**Comment by jcs090218** [comment]
@StrictlyMonad Thanks for talking to the author about this feature request. Let me know if there is any update! :)

**Comment by StrictlyMonad** [comment]
No response by far, wonder if they are still interested in this. :shrug:

That aside, the author created this repo (needs cleaning + better impl. according to the author) where they retain the changes they've tested by far: https://github.com/rainstormstudio/emacs-dashboard/tree/feat/nerd-icons

**Comment by jcs090218** [comment]
The changes look fine to me. 🤔 

cc @rainstormstudio I really enjoy nerd-icons, would you like to open a PR for this? :)

**Comment by StrictlyMonad** [comment]
Sent a DM on Reddit in case they don't check their GitHub account. Hoping for the best! :)

**Comment by rainstormstudio** [comment]
yeah sure I'm just not confident enough for that lol. I'll create a PR in one or two days after I do some more improvements :P

**Comment by rainstormstudio** [comment]
regarding the enlarged line height issue, I'm considering adding a font size option for nerd icons

**Comment by jcs090218** [comment]
That's awesome! Thanks for your flexibility! :D

**Comment by Icy-Thought** [comment]
Since the implementation has been merged to master I think it's time to close this issue. Or is there more to add here?

Nonetheless, appreciate all the effort put into this! :blush: 

Relevant PR's:
- https://github.com/emacs-dashboard/emacs-dashboard/pull/451
- https://github.com/emacs-dashboard/emacs-dashboard/pull/453

**Comment by jcs090218** [comment]
The next step is https://github.com/rainstormstudio/nerd-icons.el/issues/14.

There is nothing left we can do in this repo, therefore, closing this issue. Thanks! :D
