### ISSUE TITLE
DT's emacs setup 

### ISSUE THREAD

**Issue by NightPyHask** [emacs-dashboard/emacs-dashboard#468]
The error code is the following:  Error (use-package) : dashboard/:init: Symbol's function definition is void: dashboard-modify-heading-icons

My setup is:

(use-package dashboard
  :ensure t 
  :init
  (setq initial-buffer-choice 'dashboard-open)
  (setq dashboard-set-heading-icons t)
  (setq dashboard-set-file-icons t)
  (setq dashboard-banner-logo-title "Emacs Is More Than A Text Editor!")
  ;;(setq dashboard-startup-banner 'logo) ;; use standard emacs logo as banner
  (setq dashboard-startup-banner "/home/dt/.config/emacs/images/emacs-dash.png")  ;; use custom image as banner
  (setq dashboard-center-content nil) ;; set to 't' for centered content
  (setq dashboard-items '((recents . 5)
                          (agenda . 5 )
                          (bookmarks . 3)
                          (projects . 3)
                          (registers . 3)))
  (dashboard-modify-heading-icons '((recents . "file-text")
                              (bookmarks . "book")))
  :config
  (dashboard-setup-startup-hook))

Don't really get what its problem. Why is the function void? Anyone please?
It still functions and the dashboard is there I just want to know why does it give me this error message.

**Comment by ricardoricho** [comment]
Hi, @NightPyHask function is void because you're using it in the `:init` part of `use-package`. I guess that moving `(dashboard-modify-heading-icons...` to the `:config` part should fix the issue.

**Comment by NightPyHask** [comment]
Solved it!
Thank you.
