### ISSUE TITLE
dashboard-setup-startup-hook installs anonymous hook functions

### ISSUE THREAD

**Issue by progfolio** [emacs-dashboard/emacs-dashboard#474]
```emacs-lisp
(defun dashboard-setup-startup-hook ()
  "Setup post initialization hooks.
If a command line argument is provided, assume a filename and skip displaying
Dashboard."
  (when (< (length command-line-args) 2)
    (add-hook 'window-setup-hook (lambda ()
                                   ;; 100 means `dashboard-resize-on-hook' will run last
                                   (add-hook 'window-size-change-functions 'dashboard-resize-on-hook 100)
                                   (dashboard-resize-on-hook)))
    (add-hook 'after-init-hook (lambda ()
                                 ;; Display useful lists of items
                                 (dashboard-insert-startupify-lists)))
    (add-hook 'emacs-startup-hook (lambda ()
                                    (switch-to-buffer dashboard-buffer-name)
                                    (goto-char (point-min))
                                    (redisplay)
                                    (run-hooks 'dashboard-after-initialize-hook)))))
```
The poblem with this is two-fold:

1. It makes it difficult to remove those hooks after they are added. Elisp best practice is to name the function.

>   It works to put a lambda-expression function on a hook, but we recommend avoiding this because it can lead to confusion. If you add the same lambda-expression a second time but write it slightly differently, you will get two equivalent but distinct functions on the hook. If you then remove one of them, the other will still be on it. 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Setting-Hooks.html

2. Elpaca users are unable to add these functions to elpaca-after-init-hook easily.

I suggest giving them names so they can installation/removal is more flexible for the user.

**Comment by jcs090218** [comment]
Sounds good to me! Would you like to open a PR for this?

**Comment by progfolio** [comment]
> Sounds good to me! Would you like to open a PR for this?

Done in #475
