### ISSUE TITLE
Dashboard buffer is not visible in emacsclient -c

### ISSUE THREAD

**Issue by VentGrey** [emacs-dashboard/emacs-dashboard#477]
This might be related to #199 however I could not find any issues that address this error or it's solution.

I'm using dashboard installed from elpaca, my configuration looks like this:

```elisp
(use-package dashboard
  :elpaca t
  :ensure t
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (setq
   dashboard-items '(
                     (recents . 5)
                     (projects . 10)
                     )
   initial-buffer-choice (lambda () (get-buffer-create "*dashboard*"))
   dashboard-center-content t
   dashboard-display-icons-p t
   dashboard-icon-type 'nerd-icons
   dashboard-set-file-icons t
   dashboard-set-navigator t
   dashboard-set-init-info t
   dashboard-startup-banner "~/.config/emacs/banner.png"
   dashboard-banner-logo-title "Emacs :)"
  :init
  (dashboard-setup-startup-hook))
```

But the emacsclient doesn't show the dashboard at all. I've tried placing `initial-buffer-choice (lambda () (get-buffer-create "*dashboard*"))` in my `init.el` file, `early-init.el` and even on three files (dashboard configuration file, init and early init) at the same time but Emacs plainly ignores it. Am I missing something?

Is my elisp-fu wrong? or is Emacs doing yet another thing wrong? :thinking: 

Thanks for your time to view this issue :)

**Comment by ricardoricho** [comment]
Hi @VentGrey, well #199 is (was) a strange issue that get solved by moving the `(dashboard-setup-startup-hook)` to the `:init` section. One possible solution is to move the `(add-hook 'elpaca-...` to the `:init` section.  If that doesn't work, what is the result of running `dashboard-open`? Does it show any error or message?

**Comment by ricardoricho** [comment]
I don't use `elpaca` but maybe removing `ensure: t` and start with the basic configuration.
```emacs-lisp
;; use-package with Elpaca:
(use-package dashboard
  :elpaca t
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (dashboard-setup-startup-hook))
  ```
  The `*dashboard*` buffer I'm sure is created because of `initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")` Maybe is not loading (`(require 'dashboard)`) and using `:demand t` as`use-package` option could solve the problem.

**Comment by VentGrey** [comment]
Tried with both `:demand t` and `ensure: t` but it didn't work. Using the basic settings isn't working either. I'm trying to see if Emacs has a way of showing plugin "calls" to see if the `initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")` is failing at some point.

**Comment by VentGrey** [comment]
The `:init` section change worked but I also re-did my elpaca file structure, I think it was a synchronization issue where Emacs settings weren't being called on time.

Here's the final snippet in case anyone gets this same issue:

```elisp
(use-package dashboard
  :elpaca t
  :config
  (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
  (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
  (setq
   dashboard-center-content t
   dashboard-display-icons-p t
   dashboard-icon-type 'nerd-icons
   dashboard-set-file-icons t
   dashboard-set-navigator t
   dashboard-set-init-info t
   dashboard-startup-banner "~/.config/emacs/banner.png"
   dashboard-banner-logo-title "(E)ditor Macros")
  :init
  (dashboard-setup-startup-hook)
  (setq initial-buffer-choice (lambda () (get-buffer-create "*dashboard*"))))
```

Thank you for your support! :bowing_man:
