### ISSUE TITLE
Transparency issue with PNGs

### ISSUE THREAD

**Issue by o0nd7ots** [emacs-dashboard/emacs-dashboard#481]
This problem arose as colatteral of issue #479.

I want to have an image with transparency as my dashboard banner.
At first I started with `.svg` format and later, then advised, I switched to `.png`.
SVG hasn't got a background set and when I export it to PNG and open with Okular, it indeed is transparent.

Do any of you know what might be causing this?

**Comment by jcs090218** [comment]
FYI, I have seen this issue. But I am currently busy. I will try to get back to you as soon as I have time! 😓

**Comment by o0nd7ots** [comment]
It's good to know that you are aware of it. I decied that it is better to separate two problems into two issues.

Also this is not something urgent, so there's no need to hurry. Thank you for your time though!

**Comment by A7R7** [comment]
This is a bug of emacs, not dashboard, as it's described in https://mail.gnu.org/archive/html/bug-gnu-emacs/2022-12/msg01080.html
If you want a TRUELY transparent dashboard banner, try using XPM format image.

**Comment by o0nd7ots** [comment]
Okay, this is lame XD.

I checked it and `.webp` also works.
I wish this gets fixed by the emacs team.

It is not connected to the dashboard itself, so I close the issue
