### ISSUE TITLE
Adding margin before the logo

### ISSUE THREAD

**Issue by 8dcc** [emacs-dashboard/emacs-dashboard#485]
Is it possible to add a margin on top of the logo (or center dashboard contents vertically)?

![dashboard](https://github.com/emacs-dashboard/emacs-dashboard/assets/29655971/1fbe1a0f-cabd-492f-8b6a-30ea73d0e5b4)

In the image, it would be between the red and white line.

**Comment by jcs090218** [comment]
No, this is not possible at this moment. 🤔 However, you can have lines between each items, see centaur emacs as an example:

https://user-images.githubusercontent.com/140797/97093362-c793b000-167d-11eb-924a-1892c6e95b8a.png

**Comment by 8dcc** [comment]
I saw that in another issue, but I don't know how to get that. I tried:
```lisp
(setq dashboard-page-separator "\n\f\n")
```
But nothing. [Source](https://github.com/seagle0128/.emacs.d/blob/5a2401f431caa74e1d78b8b89c3838e53114d75c/lisp/init-dashboard.el#L89).

**Comment by jcs090218** [comment]
You will need `page-break-lines` installed.

**Comment by 8dcc** [comment]
Ah, I see. Thanks for the help.

I am closing the issue since adding the margin before the logo is not possible.
