### ISSUE TITLE
emacs client org agenda too small font

### ISSUE THREAD

**Issue by balamah** [emacs-dashboard/emacs-dashboard#488]
hello, i wanted to use emacs using emacsclient. I start as always, 
```bash
emacs --daemon
emacsclient -c -a
```

But i noticed that the org agenda font is unreadable small. Here is my font config in init.el
```emacs lisp
(add-to-list 'default-frame-alist '(font . "JetBrainsMono NFM 13")).
```

First photo is emacs client, and second is just default emacs.
![07122023-client-emacs](https://github.com/emacs-dashboard/emacs-dashboard/assets/108220598/888c16c2-26e5-4c8f-9675-51e727be059d)
![07122023-default-emacs](https://github.com/emacs-dashboard/emacs-dashboard/assets/108220598/4c95a537-0e6d-4e64-b107-67291e0494cf)

Help me to increase the org agenda size.

**Comment by ricardoricho** [comment]
Hi @balamah Usually there are different font sizes for the headlines. [Here](https://github.com/emacs-dashboard/emacs-dashboard/blob/master/dashboard-widgets.el#L1328) we're trying to "normalize" the height of the font so every dashboard item looks the same. I think that with this line `(add-to-list 'default-frame-alist '(font . "JetBrainsMono NFM 13"))` the "default" height of the headline is not set correctly. Could you try with `(set-frame-font "JetBreainsMono NFM 13")` instead?

**Comment by balamah** [comment]
i tried, to use (set-frame-font "JetBreainsMono NFM 13"), and everything was tiny. I figured out what's the problem i resized headers size
```elisp
  (with-eval-after-load 'org-faces
    (dolist (face '((org-level-1 . 1.3)
                    (org-level-2 . 1.2)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.02)
                    (org-level-5 . 1.02)
                    (org-level-6 . 1.02)
                    (org-level-7 . 1.02)
                    (org-level-8 . 1.02)))
        (set-face-attribute (car face) nil :font "JetBrainsMono NFM" :height (cdr face))))
```
But i don't know, how to resize header size only in buffers

**Comment by ricardoricho** [comment]
[We are ignoring](https://github.com/emacs-dashboard/emacs-dashboard/blob/54b7767b79fb7b9966c48a31a9d32f372ef9ec3d/dashboard-widgets.el#L1338) the height of the `org-level` faces. Maybe you can set the height on `dashboard-items-face`

**Comment by polhuang** [comment]
@balamah and anyone else who might be experiencing this, I solved this by reverting the buffer after noticing that pressing "g" solves the issue. To do this automatically, I added: 

`(add-hook 'server-after-make-frame-hook 'revert-buffer)`
