### ISSUE TITLE
How to change *dashboard* buffer name?

### ISSUE THREAD

**Issue by morgandavidson** [emacs-dashboard/emacs-dashboard#494]
I would like to change the dashboard buffer name to have a nicer tab. When I do `M-x rename-buffer RET ╰( ^o^)╮`, the buffer name can be changed easily, but when I try to implement that in emacs init it doesn't work:

```el
      (use-package dashboard
	:config
	(dashboard-setup-startup-hook)
	:custom
	(dashboard-buffer-name "╰( ^o^)╮")
```

How could `dashboard` be configured so its buffer name can be changed?

**Comment by ricardoricho** [comment]
Hi @morgandavidson, currently the buffer name is defined as a [constant](https://github.com/emacs-dashboard/emacs-dashboard/blob/00f9344e0d31b805b47c6319a37f42b485b16bf0/dashboard.el#L115). You need to change `defconst` to `defcustom`. 
As always PRs are welcome.
