### ISSUE TITLE
dashboard-remove-item-recentf

### ISSUE THREAD

**Issue by ukiran03** [emacs-dashboard/emacs-dashboard#505]
How can I prevent bookmarked files from appearing in the "Recents Files" widget upon the first startup? It was intended to display only the last opened files, right?

**Comment by jcs090218** [comment]
`recentf` records every files that entered. Try tweak the variable `recentf-exclude` to exclude the file you don't want to see.

**Comment by ukiran03** [comment]
Thank you, I will figure it out myself.
