### ISSUE TITLE
Deprecate some dashboard options?

### ISSUE THREAD

**Issue by DevelopmentCool2449** [emacs-dashboard/emacs-dashboard#508]
Hello, I was wondering if it is good idea deprecating and/or
changing some user options since dashboard-startupify-list now allows displaying or not them.

Here are the options to consider:
- deprecate dashboard-set-navigator, dashboard-set-init-info and dashboard-set-footer.
- delete nil value from dashboard-startup-banner.

**Comment by jcs090218** [comment]
Yes, you are right. 🤔 we should deprecate those options.
