### ISSUE TITLE
emacs-dashboard adds '~/.emacs.d/recentf' and 'org-agenda-files' list to top of recent files in dashboard

### ISSUE THREAD

**Issue by vonHabsi** [emacs-dashboard/emacs-dashboard#51]
When `org-agenda` is added to the dashboard the files in `org-agenda-files` are added to the **Recent Files** list in the dashboard as well, and so is `~/.emacs.d/recentf` itself.

I suspect that the order of execution may be a factor here. Is there a way to avoid it at startup, regardless of the stage, perhaps ignoring `~/.emacs.d/recentf` and  `org-agenda-files` contents when constructing the dashboard the first time?

**Comment by rakanalh** [comment]
Hi @vonHabsi,

It happens because dashboard actually opens these files and looks inside of them to get their contents.

Can you maybe try setting your `recentf-exclude` to ignore these files?
```
(setq recentf-exclude '("/path/"))
```

**Comment by vonHabsi** [comment]
Thanks - I will look into that. I am a bit of emacs newbie.

**Comment by vonHabsi** [comment]
Does emacs have a function or a mode for opening a file which doesn't add it to the recentf list?

**Comment by rakanalh** [comment]
Not that i am aware of and i don't think so. did the recentf-exclude not work?

**Comment by jhenahan** [comment]
If anyone is looking for a specific snippet that'll work in the general case

    (setq recentf-exclude (org-agenda-files))

or, if your agenda files are symlinks (as may be the case if you sync your files with a service but symlink them to your home directory), this snippet is what I use (requires `dash.el` and `f.el`):

    (setq recentf-exclude (-map 'f-canonical (org-agenda-files))

**Comment by rakanalh** [comment]
Fixed with #83
