### ISSUE TITLE
Removal of 'nil' as valid value for dashboard-startup-banner broke my Emacs

### ISSUE THREAD

**Issue by rbodewits** [emacs-dashboard/emacs-dashboard#515]
Emacs now starts up with an "Args out of range: 0" and dashboard is no longer functional.

https://github.com/emacs-dashboard/emacs-dashboard/commit/14c281a8e9513cfc36e03cd299a9298101a0443e seems to be the commit responsible for this crime.

**Comment by jcs090218** [comment]
You can now customize it with the variable `dashboard-startupify-list` by removing the item `dashboard-insert-banner`.

**Comment by DevelopmentCool2449** [comment]
> Emacs now starts up with an "Args out of range: 0" and dashboard is no longer functional.
> 
> [14c281a](https://github.com/emacs-dashboard/emacs-dashboard/commit/14c281a8e9513cfc36e03cd299a9298101a0443e) seems to be the commit responsible for this crime.

What do you have in your `dashboard-startup-banner`?

I apologize if this caused any problems, i'll try to make a PR to fix this issue.

**Comment by DevelopmentCool2449** [comment]
I've found that setting dashboard-startup-banner to nil causes this problem (also has the same error message),
did you try disabling banner?

if so, then you should delete `dashboard-insert-banner` from `dashboard-startupify-list`.
