### ISSUE TITLE
dashboard-set-footer suddenly disappeared as a variable, breaking this functionality

### ISSUE THREAD

**Issue by rbodewits** [emacs-dashboard/emacs-dashboard#516]
https://github.com/emacs-dashboard/emacs-dashboard/commit/10e596da1e963bed6d66d02e6c4e4b90a5cf3356 looks to be where 'something' was done, but I'm guessing this isn't behaving as intended. There are no future deprecation warnings, functionality just flat out disappeared and forced me to dig through my init.

**Comment by jcs090218** [comment]
You can now customize it with the variable `dashboard-startupify-list` by removing the item `dashboard-insert-banner`.

**Comment by jcs090218** [comment]
Fixed in 5922254b7c6b011823037348b8bf6204fcdcf287.
