### ISSUE TITLE
Possible bug? Loading dashboard produces error on GUI

### ISSUE THREAD

**Issue by LionyxML** [emacs-dashboard/emacs-dashboard#522]
Hello there!

Just updated to version 20240326.344 on MELPA.

Something is wrong with dashboard, it prints on the *Message* buffer:

```
Error during redisplay: (dashboard-resize-on-hook #<frame *dashboard* - GNU Emacs at debian 0x562f3a9242f0>) signaled (args-out-of-range 0) [2 times]
```

This also prevents dashboard-mode making the buffer editable:

![image](https://github.com/emacs-dashboard/emacs-dashboard/assets/16169950/0f5b267a-f58b-4f53-a109-e241b81f452f)

I tested with just :
```lisp
(use-package dashboard
  :ensure t
  :config
(dashboard-setup-startup-hook))
```

And the error persists.

If I enter Emacs on TUI with emacs -nw tough, dashboard works fine.

Any help?

**Comment by jcs090218** [comment]
Can you try `M-x toggle-debug-on-error` and paste the backtrace log here? Thanks!

**Comment by LionyxML** [comment]
Sure!

`M-x toggle-debug-on-error` followed by `dashboard-open`:

```lisp
Debugger entered--Lisp error: (args-out-of-range 0)
  dashboard-insert-footer()
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_23>(dashboard-insert-footer)
  dashboard-insert-startupify-lists()
  dashboard-open()
  funcall-interactively(dashboard-open)
  call-interactively(dashboard-open record nil)
  command-execute(dashboard-open record)
  execute-extended-command(nil "dashboard-open" "dashboard")
  funcall-interactively(execute-extended-command nil "dashboard-open" "dashboard")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by jcs090218** [comment]
It seems like a bug from #519.

cc @DevelopmentCool2449

**Comment by DevelopmentCool2449** [comment]
I've made a PR https://github.com/emacs-dashboard/emacs-dashboard/pull/523 for this issue,
i forgot `nil` is a empty list.
Apologies 😓.

**Comment by LionyxML** [comment]
It is all working now. Thanks!
