### ISSUE TITLE
Todo list doesn't load when launching with emacsclient

### ISSUE THREAD

**Issue by ryansantos1174** [emacs-dashboard/emacs-dashboard#526]
When launching an emacsclient instance, the todo list does not fully load. I can see the tags that my todo lists have but I cannot see the todo items themselves. After refershing the buffer, the items appear correctly. This doesn't not seem to be an issue when launching an emacs instance outside of the daemon. 

Here is the relevant use-package block from my configuration: 
`(use-package dashboard
 :elpaca t
 :demand
 :custom
 (dashboard-startup-banner 2)
 (dashboard-display-icons-p t)
 (dashboard-set-navigator t)
 (dashboard-set-heading-icons t)
 (dashboard-set-file-icons t)
 (dashboard-icon-type 'nerd-icons)
 (dashboard-center-content t)
 (dashboard-show-shortcuts nil)
 (dashboard-items '(
                     (bookmarks . 5)
                     (agenda . 5)))
 (dashboard-filter-agenda-entry 'dashboard-no-filter-agenda)
 (initial-buffer-choice (lambda () (get-buffer-create "*dashboard*")))
 :config
 (add-hook 'elpaca-after-init-hook #'dashboard-insert-startupify-lists)
 (add-hook 'elpaca-after-init-hook #'dashboard-initialize)
 
 (dashboard-setup-startup-hook))
`
Thank you for any help or guidance

**Comment by jcs090218** [comment]
I'm not sure since I don't use agenda and Elpaca. 

cc @ricardoricho Do you have any idea? 🤔

**Comment by ricardoricho** [comment]
Hi @ryansantos1174 I'm sorry, but I forgot to reply this issue. Is it still present? 
Could it be related to #488?

**Comment by ryansantos1174** [comment]
@ricardoricho  That looks identical to what I am seeing. That is probably it.
