### ISSUE TITLE
Dashboard doesn't load at startup

### ISSUE THREAD

**Issue by morgandavidson** [emacs-dashboard/emacs-dashboard#531]
Dashboard doesn't load at startup, I have Emacs splash screen instead

I have no error message, and when I do `M-x dashboard-open`, Dashboard loads without problem. Here is my config: 
```el
  (use-package dashboard
    :config (dashboard-setup-startup-hook)
    :custom
    (dashboard-buffer-name "╰( ^o^)╮")
    (dashboard-startupify-list '(dashboard-insert-newline
				 dashboard-insert-newline
				 dashboard-insert-newline
				 dashboard-insert-newline
				 dashboard-insert-newline
				 dashboard-insert-newline
				 dashboard-insert-banner
				 dashboard-insert-newline
				 dashboard-insert-init-info
				 dashboard-insert-newline
				 dashboard-insert-navigator
				 ))
    (dashboard-startup-banner hyperion-pic) ; default: Emacs logo
    (dashboard-navigator-buttons ;; format: icon title help action face prefix suffix`.
     `((
	("️" "n . Notmuch" "" (lambda (&rest _) (notmuch)))
	("" "e . Elfeed" "" (lambda (&rest _) (elfeed)))
	))
     )
    :bind (:map dashboard-mode-map
		("e" . elfeed)
		("n" . notmuch)
		)
    )
```
Note that when I remove the `:bind` part, Dashboard loads at startup.

**Comment by ricardoricho** [comment]
Hi @morgandavidson I believe that adding `:demand t` or `:ensure t` to `use-package` could solve the problem. I think that `use-package` doesn't require the package (deferred it) when using `:bind` or `:hook`.

**Comment by morgandavidson** [comment]
Hi @ricardoricho, indeed, `:demand t` or `:ensure t` worked, thank you very much! Also, `:init (dashboard-open)` did work.
