### ISSUE TITLE
Dashboard agenda does not show today's agenda

### ISSUE THREAD

**Issue by Emacs-is-my-life** [emacs-dashboard/emacs-dashboard#533]
Hello
I added (setq dashboard-week-agenda t) in emacs config
Now dashboard shows agendas from tomorrow till the end of this week but not today's agendas.
org-agenda-list shows all agendas including today's just fine

**Comment by jcs090218** [comment]
cc @ricardoricho

**Comment by ricardoricho** [comment]
Hi @Emacs-is-my-life. It should show today's entries but those with a time stamp after [`current-time`](https://github.com/emacs-dashboard/emacs-dashboard/blob/3852301f9c6f3104d9cc98389612b5ef3452a7de/dashboard-widgets.el#L1470).

**Comment by Emacs-is-my-life** [comment]
> Hi @Emacs-is-my-life. It should show today's entries but those with a time stamp after [`current-time`](https://github.com/emacs-dashboard/emacs-dashboard/blob/3852301f9c6f3104d9cc98389612b5ef3452a7de/dashboard-widgets.el#L1470).
> 
> If you want to include before `now` I think is easier if you define your own filter function, and set it to `dashboard-filter-agenda-entry`

Thank you. That must be the issue.
How do you add timestamp to your TODOs for agenda?
I use `C-c .`  but it only marks <YEAR-MONTH-DAY> but no time of the day

**Comment by Emacs-is-my-life** [comment]
.
