### ISSUE TITLE
Cons in `dashboard-startup-banner` fails with "wrong type argument"

### ISSUE THREAD

**Issue by winkelnp** [emacs-dashboard/emacs-dashboard#551]
When I try to set
`(setq dashboard-startup-banner ("splash.svg" . "splash.txt"))`
I get the following message in the message buffer:
`widget-default-prompt-value: Wrong type argument: listp, "splash.txt"`

Am I constructing the argument wrong or is this a bug?

**Comment by jcs090218** [comment]
List is an invalid value, see https://github.com/emacs-dashboard/emacs-dashboard?tab=readme-ov-file#configuration.

**Comment by winkelnp** [comment]
Looks like the issue was a missing ' in front of the list. I don't believe this is included in the README like it is for `'official` and `'logo`

(yes this was predominantly caused by my unfamiliarity with elisp, might still be a good idea to put this in the readme)

**Comment by jcs090218** [comment]
I forgot this feature was added in #510. 😅 

Yes, you are missing `'` in front of the bracket. Or, you can do:

```elisp
(setq dashboard-startup-banner (cons "splash.svg" "splash.txt"))
```

> might still be a good idea to put this in the readme)

Would you like to open a PR for this? :)
