### ISSUE TITLE
File paths not shortening

### ISSUE THREAD

**Issue by NicoloZorzetto** [emacs-dashboard/emacs-dashboard#554]
Why don't my file paths get shortened?
I am running Emacs 29.4 on Ubuntu and have this in my config:

```
 (use-package dashboard
    :ensure t
    :init
    (setq initial-buffer-choice 'dashboard-open)
    :config
    (dashboard-setup-startup-hook)
    :custom
    (dashboard-path-style "Truncate the beginning part of the path")
    (dashboard-shorten-by-window-width t)
    (dashboard-path-max-lenght 20)

    (dashboard-startup-banner 'official)
    (dashboard-banner-logo-title "Welcome back, Nicolò")
    (dashboard-center-content t)
    ;; (dashboard-vertically-center-content t)
    (dashboard-icon-type 'all-the-icons)
    (dashboard-set-heading-icons t)
    (dashboard-set-file-icons t)

    (dashboard-items '((recents     . 4)
			    (bookmarks   . 4)))
    (dashboard-heading-icons '((recents      . "history")
				    (bookmarks    . "bookmark")))
    (dashboard-navigation-cycle t)

    (dashboard-set-footer nil)

    )
```

Even setting the max path length to 20 won't stop dashboard from putting 100+ char long paths.

**Comment by NicoloZorzetto** [comment]
Found the solution:

`(dashboard-path-style "Truncate the beginning part of the path")`

Is obviously not correct. When tired you can make very stupid mistakes.

Correction:
` (dashboard-path-style 'truncate-beginning)`

**Comment by jcs090218** [comment]
It should be the symbol and not the docstring itself. :)

**Comment by jcs090218** [comment]
I'm glad you found the solution yourself! Sorry for not responding to this issue fast enough! :(

**Comment by NicoloZorzetto** [comment]
> I'm glad you found the solution yourself! Sorry for not responding to this issue fast enough! :(

No worries, was pretty obvious to fresh eyes, sorry for opening an entire issue for something like this
