### ISSUE TITLE
Emacs freezes as soon as dashboard is loaded

### ISSUE THREAD

**Issue by winkelnp** [emacs-dashboard/emacs-dashboard#557]
Issue: when `dashboard-open` is run emacs freezes up and runs a single CPU core at 100% until process is terminated.

I could confirm that this doesn't happen when I disable `initial-buffer-choice`, and then only occurs when `dashboard-open` is run.

I could however not generate any logs as it freezes immediately along with all other emacsclient windows, so I couldn't see any further messages (independent emacs instances are unaffected). Is there a method I am missing to generate more detailed logs/error messages?

**Comment by ricardoricho** [comment]
Hi, most of the items in dashboard depends on other packages, for example, agenda depends on `org-agenda`, projects could depend on `project.el` or `projectile`, recent files on `recentf.el` and so on.
Some users had report issues with [TRAMP and bookmarks](https://github.com/emacs-dashboard/emacs-dashboard/issues/408) .
Maybe you could start with just one item in `dashboard-items` and see which one "breaks" or "hangs".

**Comment by winkelnp** [comment]
Whatever package was causing this seems to have fixed it, I no longer seem to get the crashes. No clue what it was or what I updated in the mean time ...

**Comment by winkelnp** [comment]
Whatever package caused this seems to have patched it. I no longer seem to get the freezes, have no clue what caused this or what package I updated to fix it...
