### ISSUE TITLE
Can I move the text of bookmark, recentf, etc, to the center

### ISSUE THREAD

**Issue by Ninlives** [emacs-dashboard/emacs-dashboard#77]
On my screen they seems to be too "left".

**Comment by rakanalh** [comment]
At the moment, this is not implemented in Dashboard... would love to receive a PR if you would like to tackle this issue.

**Comment by Bee-Mar** [comment]
This is something that's working temporarily. Quite honestly, I'm still trying to understand Elisp, so, there's a lot to be desired, but it's possibly a start for someone to tidy up.

![2019-02-05-105216_1912x1049_scrot](https://user-images.githubusercontent.com/17814198/52285330-22c6c180-2934-11e9-9070-1d32e0bcf994.png)

`(defun center-dashboard()
  (if (eq buffer-file-name "*dashboard*")
      (set-fringe-style nil)
    (set-fringe-mode
     (/ (- (frame-pixel-width)
           (* 66 (frame-char-width)))
        2))))

(add-hook 'dashboard-mode-hook 'center-dashboard)`

**Comment by JesusMtnez** [comment]
Done #88
