### ISSUE TITLE
Customization group “dashboard” is a member of… itself

### ISSUE THREAD

**Issue by TinaRussell** [emacs-dashboard/emacs-dashboard#95]
In dashboard.el:
```
(defgroup dashboard nil
  "Settings that are used in the Dashboard"
  :group 'dashboard)
```
The `:group 'dashboard` part makes the Dashboard customization group both its own parent and its own subgroup. It doesn’t cause any runtime problems, it just means that the Dashboard group is missing from the customization hierarchy, and points to itself as both a parent and a subgroup.
Anyway, it just means we need to pick a group of which Dashboard _should_ be a part. I’d say `startup` (used by `use-package`) makes the most sense, though (at least on my Emacs) it’s missing a group definition and thus isn’t part of the customization hierarchy either… but that‘s Wiegley’s fault, not ours :wink:

**Comment by jkdufair** [comment]
@TinaRussell What about `Applications` or `Convenience`?

**Comment by TinaRussell** [comment]
Either sounds good to me
