### ISSUE TITLE
Can org-agenda be optional?

### ISSUE THREAD

**Issue by seagle0128** [emacs-dashboard/emacs-dashboard#96]
Since it's slow to load `org` package, can it be optional if it's not used in `dashboard`?

**Comment by JesusMtnez** [comment]
You could configure `dashboard-items` to not include `agenda` so it is not loaded.

For example, this is my current configuration:
```elisp
(setq dashboard-items '((recents  . 5)
                        (projects . 5)))
```

**Comment by seagle0128** [comment]
My setting is below:

```elisp
(setq dashboard-items '((recents  . 10)
                        (bookmarks . 5)
                        (projects . 5)))
```

I think `org` will be loaded since there is `(require 'org-agenda)` in `dashboard.el`.

**Comment by seagle0128** [comment]
Thank you!
