### ISSUE TITLE
Shortcuts don't work

### ISSUE THREAD

**Issue by seagle0128** [emacs-dashboard/emacs-dashboard#97]
OS: macOS Mojave
GNU Emacs: 26.1
Version: 29ecbd87f2bd0bcc47ac09dcc09c09958035324d 

All section shortcuts don't work in the latest version, while they worked well before.
e.g. `r` should jump to `Recent files`.

**Comment by JesusMtnez** [comment]
Hi @seagle0128 that's weird. I've just updated this morning and shortcuts worked perfectly :thinking: I also use Emacs 26.1 (on Linux)

Could you share your Emacs / Dashboard configuration file? Maybe there is a misconfiguration :thinking:

**Comment by seagle0128** [comment]
Thanks for the quick reply!
I noticed there is a recent change related to compilation, then I deleted and reinstalled the package. It works well again!

**Comment by seagle0128** [comment]
Sorry, it's too fast to say it's fine now.
After restarting the Emacs, it doesn't work again!
My configuration is here: https://github.com/seagle0128/.emacs.d/blob/master/lisp/init-dashboard.el

**Comment by JesusMtnez** [comment]
@seagle0128 you are right, just opened my emacs and no bindings are not working :thinking:

**Comment by jkdufair** [comment]
This seems to happen if `dashboard-widgets.el` gets byte-compiled. I'll dig in and try to figure this out.

**Comment by seagle0128** [comment]
Thanks for the fixing! It works well now.
