### ISSUE TITLE
Setting "dashboard-center-content" breaks emacsclient

### ISSUE THREAD

**Issue by Bee-Mar** [emacs-dashboard/emacs-dashboard#98]
When `dashboard-center-content` is set to `t` the emacsclient hangs on startup, and a frame cannot be opened. However, opening Emacs without using the daemon is just fine. When setting  `dashboard-center-content` back to `nil`, the emacsclient and daemon work as expected. Also, there are no error messages displayed when opening Emacs after setting  `dashboard-center-content` to `t` and opening a normal instance of Emacs.

OS: Ubuntu 18.04
Emacs Version: 26.1

```
(use-package dashboard
  :diminish dashboard-mode
  :config

  (use-package dashboard-hackernews)
  (use-package page-break-lines)

  (dashboard-insert-shortcut "h" "Hackernews")

  (setq dashboard-page-separator "\n\n"
        show-week-agenda-p t
        dashboard-center-content nil            ;; if set to t, emacsclient no longer works
        dashboard-banner-logo-title ""
        dashboard-startup-banner "~/Pictures/gnu-logo-green.png"
        dashboard-items '((agenda . 10)
                          (hackernews . 5)
                          (bookmarks . 7)))
  
  (defun detailed-dashboard-banner ()
    "Dashboard banner prints startup time."
    (setq dashboard-banner-logo-title
          (format "Emacs locked and loaded in %.2f seconds."
                  (float-time (time-subtract after-init-time before-init-time)))))

  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  (add-hook 'dashboard-mode-hook 'detailed-dashboard-banner)

  (dashboard-setup-startup-hook))
```

**Comment by JesusMtnez** [comment]
@Bee-Mar I've just tried what you suggested, and I got this error in from `*Messages*` buffer:

```
// emacsclient -c
Error during redisplay: (dashboard-resize-on-hook #<frame emacs@Sirius 0x1427c80>) signaled (wrong-type-argument wholenump -2)
//emacsclient -t
Error during redisplay: (dashboard-resize-on-hook #<frame F2 0x71276f0>) signaled (wrong-type-argument wholenump -1)
```

I'll try to debug it when I have some spare time! Thank you!

**Comment by Bee-Mar** [comment]
Sounds good! And thank you for working on this pull-request! When I saw this was submitted I got pretty excited haha

**Comment by JesusMtnez** [comment]
All thanks to @jkdufair who did an amazing job there.

**Comment by jkdufair** [comment]
I can also try to dig in and at least try to get it not to choke!
